const data = {
  0: {
    groups: [
      {
        number: 1,
        theme: "Estabelecimentos educacionais",
        words: ["liceu", "escola", "ginásio", "instituto"],
      },
      {
        number: 2,
        theme: "Comida",
        words: ["merenda", "provisão", "refeição", "lanche"],
      },
      {
        number: 3,
        theme: "Cargos no mercado financeiro",
        words: ["traders", "investidores", "contadores", "economistas"],
      },
      {
        number: 4,
        theme: "Bairros do Rio de Janeiro",
        words: ["zumbi", "colégio", "bancários", "recreio"],
      },
    ],
    startingBoard: [
      "provisão",
      "liceu",
      "contadores",
      "ginásio",
      "bancários",
      "recreio",
      "refeição",
      "economistas",
      "escola",
      "lanche",
      "zumbi",
      "merenda",
      "instituto",
      "investidores",
      "colégio",
      "traders",
    ],
  },
  1: {
    groups: [
      {
        number: 1,
        theme: "Cômodos da casa",
        words: ["varanda", "lavabo", "sala", "quarto"],
      },
      {
        number: 2,
        theme: "Atletas",
        words: ["corredor", "ciclista", "nadador", "ginasta"],
      },
      {
        number: 3,
        theme: "Une",
        words: ["conecta", "junta", "ata", "acopla"],
      },
      {
        number: 4,
        theme: "Eventos esportivos",
        words: ["olimpíada", "copa", "maratona", "liga"],
      },
    ],
    startingBoard: [
      "quarto",
      "copa",
      "ginasta",
      "liga",
      "conecta",
      "ata",
      "corredor",
      "olimpíada",
      "lavabo",
      "nadador",
      "junta",
      "acopla",
      "ciclista",
      "sala",
      "maratona",
      "varanda",
    ],
  },
  2: {
    groups: [
      {
        number: 1,
        theme: "Meios de transporte",
        words: ["barco", "caminhão", "helicóptero", "bicicleta"],
      },
      {
        number: 2,
        theme: "Encontrados na academia",
        words: ["esteira", "espelho", "instrutor", "halteres"],
      },
      {
        number: 3,
        theme: "Têm formato cilíndrico",
        words: ["cigarro", "canudo", "vela", "cano"],
      },
      {
        number: 4,
        theme: "Lost",
        words: ["fumaça", "números", "ilha", "avião"],
      },
    ],
    startingBoard: [
      "vela",
      "bicicleta",
      "fumaça",
      "cigarro",
      "números",
      "barco",
      "instrutor",
      "caminhão",
      "esteira",
      "espelho",
      "ilha",
      "cano",
      "helicóptero",
      "canudo",
      "avião",
      "halteres",
    ],
  },
  3: {
    groups: [
      {
        number: 1,
        theme: "Itens de papelaria",
        words: ["lápis", "pasta", "caderno", "bloco"],
      },
      {
        number: 2,
        theme: "Feijão ___",
        words: ["gordo", "fradinho", "tropeiro", "amigo"],
      },
      {
        number: 3,
        theme: "Companheiro",
        words: ["camarada", "colega", "comparsa", "aliado"],
      },
      {
        number: 4,
        theme: "Tipos de saia",
        words: ["maxi", "tulipa", "envelope", "tutu"],
      },
    ],
    startingBoard: [
      "gordo",
      "envelope",
      "caderno",
      "tropeiro",
      "aliado",
      "pasta",
      "tutu",
      "maxi",
      "bloco",
      "fradinho",
      "amigo",
      "colega",
      "camarada",
      "tulipa",
      "comparsa",
      "lápis",
    ],
  },
  4: {
    groups: [
      {
        number: 1,
        theme: "Tipos de rodízio",
        words: ["churrasco", "pizza", "comida japonesa", "caldos"],
      },
      {
        number: 2,
        theme: "Utensílios de cozinha",
        words: ["pratos", "talheres", "panelas", "copos"],
      },
      {
        number: 3,
        theme: "Itens colecionáveis",
        words: ["selos", "canecas", "cartões", "moedas"],
      },
      {
        number: 4,
        theme: "São normalmente pretos",
        words: ["carvão", "piche", "discos de vinil", "pneus"],
      },
    ],
    startingBoard: [
      "comida japonesa",
      "pizza",
      "carvão",
      "canecas",
      "talheres",
      "selos",
      "churrasco",
      "discos de vinil",
      "caldos",
      "pratos",
      "moedas",
      "cartões",
      "panelas",
      "piche",
      "copos",
      "pneus",
    ],
  },
  5: {
    groups: [
      {
        number: 1,
        theme: "Incrível",
        words: ["espetacular", "fantástico", "maravilhoso", "extraordinário"],
      },
      {
        number: 2,
        theme: "Tolo",
        words: ["trouxa", "ingênuo", "bobo", "inocente"],
      },
      {
        number: 3,
        theme: "Artistas circenses",
        words: ["palhaço", "mágico", "domador", "malabarista"],
      },
      {
        number: 4,
        theme: "Personagens de Caverna do Dragão",
        words: ["unicórnio", "mago", "acrobata", "bárbaro"],
      },
    ],
    startingBoard: [
      "maravilhoso",
      "mágico",
      "extraordinário",
      "trouxa",
      "bárbaro",
      "unicórnio",
      "palhaço",
      "inocente",
      "espetacular",
      "domador",
      "ingênuo",
      "malabarista",
      "mago",
      "fantástico",
      "bobo",
      "acrobata",
    ],
  },
  6: {
    groups: [
      {
        number: 1,
        theme: "Peças de roupa",
        words: ["camisa", "bermuda", "saia", "vestido"],
      },
      {
        number: 2,
        theme: "Biomas brasileiros",
        words: ["caatinga", "cerrado", "amazônia", "pantanal"],
      },
      {
        number: 3,
        theme: "Cantoras pop",
        words: ["gomez", "rexha", "grande", "lovato"],
      },
      {
        number: 4,
        theme: "Carros antigos",
        words: ["del rey", "regata", "belina", "pampa"],
      },
    ],
    startingBoard: [
      "cerrado",
      "saia",
      "bermuda",
      "pantanal",
      "camisa",
      "del rey",
      "lovato",
      "caatinga",
      "rexha",
      "gomez",
      "amazônia",
      "grande",
      "pampa",
      "regata",
      "vestido",
      "belina",
    ],
  },
  7: {
    groups: [
      {
        number: 1,
        theme: "Completo",
        words: ["integral", "total", "pleno", "absoluto"],
      },
      {
        number: 2,
        theme: "Cargo",
        words: ["posição", "ofício", "competência", "ocupação"],
      },
      {
        number: 3,
        theme: "Parcela",
        words: ["parte", "fração", "pedaço", "quota"],
      },
      {
        number: 4,
        theme: "Termos da matemática",
        words: ["raiz", "função", "ponto", "derivada"],
      },
    ],
    startingBoard: [
      "fração",
      "integral",
      "quota",
      "pedaço",
      "função",
      "pleno",
      "ocupação",
      "absoluto",
      "competência",
      "ofício",
      "ponto",
      "parte",
      "raiz",
      "derivada",
      "posição",
      "total",
    ],
  },
  8: {
    groups: [
      {
        number: 1,
        theme: "Recordação",
        words: ["memória", "lembrança", "souvenir", "mimo"],
      },
      {
        number: 2,
        theme: "Componentes de um computador",
        words: ["cooler", "processador", "placa de vídeo", "ssd"],
      },
      {
        number: 3,
        theme: "Tipos de cabos",
        words: ["rede", "hdmi", "usb", "lightning"],
      },
      {
        number: 4,
        theme: "Jogo da(do) ___",
        words: ["vida", "velha", "forca", "bicho"],
      },
    ],
    startingBoard: [
      "processador",
      "cooler",
      "vida",
      "forca",
      "rede",
      "souvenir",
      "usb",
      "lightning",
      "bicho",
      "hdmi",
      "lembrança",
      "velha",
      "memória",
      "ssd",
      "mimo",
      "placa de vídeo",
    ],
  },
  9: {
    groups: [
      {
        number: 1,
        theme: "Frutas cítricas",
        words: ["laranja", "tangerina", "pomelo", "abacaxi"],
      },
      {
        number: 2,
        theme: "Bebidas alcoólicas",
        words: ["vermute", "vodca", "tequila", "gim"],
      },
      {
        number: 3,
        theme: "Ervas aromáticas",
        words: ["manjericão", "alecrim", "segurelha", "tomilho"],
      },
      {
        number: 4,
        theme: "Mojito",
        words: ["rum", "hortelã", "limão", "água com gás"],
      },
    ],
    startingBoard: [
      "laranja",
      "segurelha",
      "rum",
      "alecrim",
      "hortelã",
      "água com gás",
      "pomelo",
      "vermute",
      "tequila",
      "manjericão",
      "vodca",
      "tomilho",
      "tangerina",
      "gim",
      "abacaxi",
      "limão",
    ],
  },
  10: {
    groups: [
      {
        number: 1,
        theme: "Fenômenos meteorológicos",
        words: ["tornado", "tempestade", "granizo", "ciclone"],
      },
      {
        number: 2,
        theme: "Transcendental",
        words: ["mística", "mágica", "esotérica", "metafísica"],
      },
      {
        number: 3,
        theme: "Criaturas mitológicas",
        words: ["sereia", "grifo", "ciclope", "centauro"],
      },
      {
        number: 4,
        theme: "Personagens de Hora da Aventura",
        words: ["cachorro", "rei", "vampira", "console"],
      },
    ],
    startingBoard: [
      "grifo",
      "mística",
      "rei",
      "tempestade",
      "mágica",
      "granizo",
      "sereia",
      "metafísica",
      "tornado",
      "cachorro",
      "ciclone",
      "ciclope",
      "esotérica",
      "centauro",
      "vampira",
      "console",
    ],
  },
  11: {
    groups: [
      {
        number: 1,
        theme: "Partes superiores de residências ",
        words: ["telhado", "terraço", "cobertura", "laje"],
      },
      {
        number: 2,
        theme: "Sundae",
        words: ["sorvete", "chantilly", "calda", "cereja"],
      },
      {
        number: 3,
        theme: "Frutas",
        words: ["pêssego", "ameixa", "abacaxi", "figo"],
      },
      {
        number: 4,
        theme: "Sinônimos de limite",
        words: ["teto", "máximo", "barreira", "fronteira"],
      },
    ],
    startingBoard: [
      "chantilly",
      "ameixa",
      "abacaxi",
      "telhado",
      "teto",
      "sorvete",
      "cereja",
      "fronteira",
      "pêssego",
      "máximo",
      "barreira",
      "terraço",
      "figo",
      "laje",
      "cobertura",
      "calda",
    ],
  },
  12: {
    groups: [
      {
        number: 1,
        theme: "Números primos",
        words: ["um", "dois", "três", "cinco"],
      },
      {
        number: 2,
        theme: "Branca de Neve",
        words: ["espelho", "maçã", "mina", "sete"],
      },
      {
        number: 3,
        theme: "Marcas de leite condensado",
        words: ["moça", "mococa", "itambé", "piracanjuba"],
      },
      {
        number: 4,
        theme: "Cidades na Bahia",
        words: ["salvador", "ilhéus", "irecê", "camaçari"],
      },
    ],
    startingBoard: [
      "camaçari",
      "mococa",
      "salvador",
      "dois",
      "irecê",
      "itambé",
      "mina",
      "três",
      "maçã",
      "um",
      "sete",
      "piracanjuba",
      "cinco",
      "espelho",
      "ilhéus",
      "moça",
    ],
  },
  13: {
    groups: [
      {
        number: 1,
        theme: "Aviamentos",
        words: ["fivelas", "renda", "paetês", "botões"],
      },
      {
        number: 2,
        theme: "Sinais de pontuação",
        words: ["chaves", "colchetes", "parênteses", "aspas"],
      },
      {
        number: 3,
        theme: "Mídias obsoletas",
        words: ["fitas", "vinis", "cds", "dvds"],
      },
      {
        number: 4,
        theme: "Termos financeiros",
        words: ["lucro", "receita", "provento", "rendimento"],
      },
    ],
    startingBoard: [
      "lucro",
      "chaves",
      "cds",
      "parênteses",
      "rendimento",
      "renda",
      "aspas",
      "receita",
      "botões",
      "vinis",
      "fitas",
      "paetês",
      "dvds",
      "provento",
      "fivelas",
      "colchetes",
    ],
  },
  14: {
    groups: [
      {
        number: 1,
        theme: "Meios de transporte",
        words: ["avião", "metrô", "ônibus", "barco"],
      },
      {
        number: 2,
        theme: "Estática",
        words: ["imóvel", "inerte", "estacionária", "fixa"],
      },
      {
        number: 3,
        theme: "Empresa",
        words: ["firma", "companhia", "estabelecimento", "corporação"],
      },
      {
        number: 4,
        theme: "Gírias para coisa",
        words: ["parada", "treco", "negócio", "trem"],
      },
    ],
    startingBoard: [
      "negócio",
      "imóvel",
      "metrô",
      "estabelecimento",
      "firma",
      "barco",
      "trem",
      "ônibus",
      "avião",
      "parada",
      "inerte",
      "fixa",
      "companhia",
      "estacionária",
      "corporação",
      "treco",
    ],
  },
  15: {
    groups: [
      {
        number: 1,
        theme: "Itens de cuidado com o bebê",
        words: ["lencinho", "babador", "mamadeira", "chupeta"],
      },
      {
        number: 2,
        theme: "Falsifica",
        words: ["frauda", "forja", "adultera", "manipula"],
      },
      {
        number: 3,
        theme: "Pós brancos",
        words: ["sal", "talco", "farinha", "fermento"],
      },
      {
        number: 4,
        theme: "Cobra cascavel",
        words: ["escama", "chocalho", "veneno", "presa"],
      },
    ],
    startingBoard: [
      "escama",
      "chocalho",
      "manipula",
      "lencinho",
      "fermento",
      "adultera",
      "babador",
      "frauda",
      "talco",
      "mamadeira",
      "veneno",
      "presa",
      "chupeta",
      "forja",
      "farinha",
      "sal",
    ],
  },
  16: {
    groups: [
      {
        number: 1,
        theme: "Estabelecimentos de hospedagem",
        words: ["albergue", "pensão", "pousada", "resort"],
      },
      {
        number: 2,
        theme: "Banco imobiliário",
        words: ["prisão", "hotel", "dinheiro", "dados"],
      },
      {
        number: 3,
        theme: "Orkut",
        words: ["perfil", "comunidade", "testemunho", "scrap"],
      },
      {
        number: 4,
        theme: "Reação (em) ___",
        words: ["alérgica", "química", "adversa", "cadeia"],
      },
    ],
    startingBoard: [
      "hotel",
      "prisão",
      "testemunho",
      "adversa",
      "pousada",
      "scrap",
      "albergue",
      "química",
      "resort",
      "alérgica",
      "pensão",
      "perfil",
      "comunidade",
      "cadeia",
      "dinheiro",
      "dados",
    ],
  },
  17: {
    groups: [
      {
        number: 1,
        theme: "Tipos de animais",
        words: ["bovino", "felino", "primata", "suíno"],
      },
      {
        number: 2,
        theme: "Dentes",
        words: ["molar", "canino", "incisivo", "siso"],
      },
      {
        number: 3,
        theme: "Categórico",
        words: ["claro", "direto", "nítido", "contundente"],
      },
      {
        number: 4,
        theme: "Incolor",
        words: ["cristalino", "límpido", "transparente", "translúcido"],
      },
    ],
    startingBoard: [
      "incisivo",
      "siso",
      "felino",
      "nítido",
      "cristalino",
      "primata",
      "claro",
      "translúcido",
      "suíno",
      "transparente",
      "bovino",
      "direto",
      "límpido",
      "contundente",
      "molar",
      "canino",
    ],
  },
  18: {
    groups: [
      {
        number: 1,
        theme: "Frutas",
        words: ["romã", "morango", "ameixa", "amora"],
      },
      {
        number: 2,
        theme: "Tipos de couve",
        words: ["manteiga", "flor", "galega", "bruxelas"],
      },
      {
        number: 3,
        theme: "Capitais na Europa",
        words: ["praga", "amsterdã", "lisboa", "paris"],
      },
      {
        number: 4,
        theme: "Podemos passar no pão",
        words: ["geléia", "requeijão", "patê", "margarina"],
      },
    ],
    startingBoard: [
      "margarina",
      "romã",
      "praga",
      "galega",
      "ameixa",
      "lisboa",
      "flor",
      "patê",
      "manteiga",
      "morango",
      "bruxelas",
      "amora",
      "requeijão",
      "geléia",
      "paris",
      "amsterdã",
    ],
  },
  19: {
    groups: [
      {
        number: 1,
        theme: "Meios de transporte",
        words: ["bicicleta", "canoa", "skate", "patins"],
      },
      {
        number: 2,
        theme: "Brinquedos",
        words: ["papagaio", "bola", "carrinho", "boneca"],
      },
      {
        number: 3,
        theme: "Aves",
        words: ["coruja", "maritaca", "cegonha", "gaivota"],
      },
      {
        number: 4,
        theme: "Usados para armazenar roupas",
        words: ["arara", "mala", "gaveta", "closet"],
      },
    ],
    startingBoard: [
      "coruja",
      "patins",
      "gaivota",
      "carrinho",
      "arara",
      "papagaio",
      "canoa",
      "maritaca",
      "boneca",
      "closet",
      "gaveta",
      "skate",
      "mala",
      "bola",
      "bicicleta",
      "cegonha",
    ],
  },
  20: {
    groups: [
      {
        number: 1,
        theme: "Wando - Fogo e Paixão",
        words: ["luz", "raio", "estrela", "luar"],
      },
      {
        number: 2,
        theme: "Celebrações",
        words: ["aniversário", "casamento", "chá", "formatura"],
      },
      {
        number: 3,
        theme: "Relativos a círculos",
        words: ["setor", "tangente", "centro", "diâmetro"],
      },
      {
        number: 4,
        theme: "Manobras de ginástica",
        words: ["mortal", "twist", "giro", "cambalhota"],
      },
    ],
    startingBoard: [
      "luar",
      "tangente",
      "luz",
      "cambalhota",
      "raio",
      "casamento",
      "setor",
      "diâmetro",
      "twist",
      "formatura",
      "giro",
      "chá",
      "estrela",
      "centro",
      "mortal",
      "aniversário",
    ],
  },
  21: {
    groups: [
      {
        number: 1,
        theme: "Materiais de costura",
        words: ["linha", "dedal", "agulha", "alfinete"],
      },
      {
        number: 2,
        theme: "Frutas",
        words: ["goiaba", "maracujá", "abacate", "figo"],
      },
      {
        number: 3,
        theme: "Peixe-___",
        words: ["espada", "boi", "lua", "borboleta"],
      },
      {
        number: 4,
        theme: "Remetem aos personagens de Turma da Mônica",
        words: ["plano", "coelho", "guarda-chuva", "melancia"],
      },
    ],
    startingBoard: [
      "espada",
      "coelho",
      "borboleta",
      "boi",
      "figo",
      "maracujá",
      "plano",
      "abacate",
      "lua",
      "linha",
      "alfinete",
      "goiaba",
      "dedal",
      "melancia",
      "guarda-chuva",
      "agulha",
    ],
  },
  22: {
    groups: [
      {
        number: 1,
        theme: "Preço",
        words: ["quantia", "valor", "custo", "investimento"],
      },
      {
        number: 2,
        theme: "Acessórios",
        words: ["bolsa", "gravata", "cinto", "chapéu"],
      },
      {
        number: 3,
        theme: "Técnicas futebolísticas",
        words: ["caneta", "bicicleta", "roleta", "pedalada"],
      },
      {
        number: 4,
        theme: "São expressados por verbos",
        words: ["ação", "estado", "fenômeno ", "ocorrência "],
      },
    ],
    startingBoard: [
      "custo",
      "quantia",
      "bicicleta",
      "investimento",
      "ação",
      "cinto",
      "bolsa",
      "estado",
      "roleta",
      "fenômeno ",
      "ocorrência ",
      "chapéu",
      "gravata",
      "valor",
      "caneta",
      "pedalada",
    ],
  },
  23: {
    groups: [
      {
        number: 1,
        theme: "Que se aplica ou estende a tudo/todos",
        words: ["geral", "global", "comum", "total"],
      },
      {
        number: 2,
        theme: "Formas de ingressar no ensino superior",
        words: ["enem", "fies", "sisu", "prouni"],
      },
      {
        number: 3,
        theme: "Estúdios de cinema",
        words: ["universal", "columbia", "lionsgate", "paramount"],
      },
      {
        number: 4,
        theme: "Têm um leão como símbolo",
        words: ["irpf", "proerd", "mgm", "peugeot"],
      },
    ],
    startingBoard: [
      "proerd",
      "peugeot",
      "paramount",
      "total",
      "prouni",
      "global",
      "comum",
      "fies",
      "columbia",
      "lionsgate",
      "mgm",
      "universal",
      "enem",
      "sisu",
      "geral",
      "irpf",
    ],
  },
  24: {
    groups: [
      {
        number: 1,
        theme: "Grupos de axé",
        words: ["chiclete", "eva", "harmonia", "jamil"],
      },
      {
        number: 2,
        theme: "Guloseimas",
        words: ["biscoito", "chocolate", "bala", "pirulito"],
      },
      {
        number: 3,
        theme: "Uniformidade",
        words: ["ordem", "equilíbrio", "proporção", "simetria"],
      },
      {
        number: 4,
        theme: "Sinônimos de fofoca",
        words: ["fuxico", "boato", "babado", "mexerico"],
      },
    ],
    startingBoard: [
      "chocolate",
      "proporção",
      "babado",
      "simetria",
      "fuxico",
      "pirulito",
      "jamil",
      "mexerico",
      "equilíbrio",
      "eva",
      "biscoito",
      "boato",
      "ordem",
      "bala",
      "harmonia",
      "chiclete",
    ],
  },
  25: {
    groups: [
      {
        number: 1,
        theme: "Tipos de navio",
        words: ["carga", "pesca", "cruzeiro", "guerra"],
      },
      {
        number: 2,
        theme: "Mercadoria",
        words: ["fardo", "encomenda", "lote", "remessa"],
      },
      {
        number: 3,
        theme: "Agremiação",
        words: ["grêmio", "assembléia", "círculo", "clube"],
      },
      {
        number: 4,
        theme: "Times de futebol",
        words: ["internacional", "atlético", "vasco", "ferroviária"],
      },
    ],
    startingBoard: [
      "vasco",
      "guerra",
      "carga",
      "fardo",
      "grêmio",
      "lote",
      "ferroviária",
      "internacional",
      "círculo",
      "remessa",
      "clube",
      "encomenda",
      "atlético",
      "cruzeiro",
      "pesca",
      "assembléia",
    ],
  },
  26: {
    groups: [
      {
        number: 1,
        theme: "Regra",
        words: ["norma", "regulamento", "princípio", "determinação"],
      },
      {
        number: 2,
        theme: "Configurações de uma câmera fotográfica",
        words: ["abertura", "iso", "velocidade", "exposição"],
      },
      {
        number: 3,
        theme: "Autarquias federais brasileiras",
        words: ["anvisa", "inmetro", "aneel", "ibge"],
      },
      {
        number: 4,
        theme: "Componentes de uma parábola (matemática)",
        words: ["vértice", "foco", "parâmetro", "diretriz"],
      },
    ],
    startingBoard: [
      "regulamento",
      "anvisa",
      "parâmetro",
      "inmetro",
      "vértice",
      "velocidade",
      "exposição",
      "norma",
      "iso",
      "foco",
      "determinação",
      "diretriz",
      "princípio",
      "ibge",
      "aneel",
      "abertura",
    ],
  },
  27: {
    groups: [
      {
        number: 1,
        theme: "Adjetivos pátrios brasileiros",
        words: ["paulista", "goiano", "capixaba", "mineiro"],
      },
      {
        number: 2,
        theme: "Comumente feitos de madeira",
        words: ["caixão", "porta", "palete", "lápis"],
      },
      {
        number: 3,
        theme: "Zé ___",
        words: ["carioca", "gotinha", "colmeia", "ramalho"],
      },
      {
        number: 4,
        theme: "Tropa de Elite",
        words: ["baiano", "caveira", "nascimento", "02"],
      },
    ],
    startingBoard: [
      "colmeia",
      "paulista",
      "02",
      "baiano",
      "caixão",
      "nascimento",
      "mineiro",
      "porta",
      "goiano",
      "capixaba",
      "ramalho",
      "lápis",
      "caveira",
      "gotinha",
      "palete",
      "carioca",
    ],
  },
  28: {
    groups: [
      {
        number: 1,
        theme: "Tem no mar",
        words: ["coral", "alga", "recife", "sargaço"],
      },
      {
        number: 2,
        theme: "Capitais brasileiras",
        words: ["manaus", "belém", "teresina", "natal"],
      },
      {
        number: 3,
        theme: "Utensílios de cozinha",
        words: ["fuê", "concha", "escumadeira", "espátula"],
      },
      {
        number: 4,
        theme: "Ferramentas utilizadas por escultores",
        words: ["macete", "cinzel", "formão", "lixa"],
      },
    ],
    startingBoard: [
      "teresina",
      "sargaço",
      "coral",
      "natal",
      "concha",
      "belém",
      "lixa",
      "macete",
      "alga",
      "fuê",
      "espátula",
      "manaus",
      "cinzel",
      "formão",
      "recife",
      "escumadeira",
    ],
  },
  29: {
    groups: [
      {
        number: 1,
        theme: "Fornecem iluminação ",
        words: ["lâmpada ", "lanterna", "abajur ", "luminária "],
      },
      {
        number: 2,
        theme: "Cidades de Minas Gerais",
        words: ["ouro preto", "diamantina", "mariana", "sabará"],
      },
      {
        number: 3,
        theme: "Seres míticos",
        words: ["vampiro", "fada", "lobisomem", "fauno"],
      },
      {
        number: 4,
        theme: "Figuras históricas brasileiras",
        words: ["zumbi", "conselheiro", "tiradentes", "lampião"],
      },
    ],
    startingBoard: [
      "fada",
      "mariana",
      "diamantina",
      "lanterna",
      "fauno",
      "lampião",
      "vampiro",
      "lobisomem",
      "conselheiro",
      "lâmpada ",
      "zumbi",
      "ouro preto",
      "tiradentes",
      "sabará",
      "luminária ",
      "abajur ",
    ],
  },
  30: {
    groups: [
      {
        number: 1,
        theme: "Roupa de cama",
        words: ["lençol", "colcha", "cobertor", "fronha"],
      },
      {
        number: 2,
        theme: "Vestimentas de inverno",
        words: ["manto", "capa", "poncho", "xale"],
      },
      {
        number: 3,
        theme: "Sinônimos de menino",
        words: ["garoto", "guri", "piá", "miúdo"],
      },
      {
        number: 4,
        theme: "Marcas de chocolate",
        words: ["lacta", "nestlé", "arcor", "ferrero"],
      },
    ],
    startingBoard: [
      "guri",
      "cobertor",
      "miúdo",
      "garoto",
      "capa",
      "lençol",
      "nestlé",
      "lacta",
      "poncho",
      "piá",
      "colcha",
      "xale",
      "arcor",
      "fronha",
      "manto",
      "ferrero",
    ],
  },
};

export const useData = () => {
  return data;
};
