const data = {
  0: {
    groups: [
      {
        number: 1,
        theme: "Objetos de iluminação",
        words: ["abajour", "lustre", "lanterna", "holofote"],
      },
      {
        number: 2,
        theme: "Personagens da Disney",
        words: ["simba", "pluto", "pumba", "bambi"],
      },
      {
        number: 3,
        theme: "Componentes de embarcações",
        words: ["popa", "mastro", "casco", "timão"],
      },
      {
        number: 4,
        theme: "Relacionados a desejos",
        words: ["vela", "poço", "estrela", "lâmpada"],
      },
    ],
    startingBoard: [
      "simba",
      "lustre",
      "lanterna",
      "lâmpada",
      "timão",
      "poço",
      "abajour",
      "vela",
      "estrela",
      "bambi",
      "pumba",
      "mastro",
      "holofote",
      "pluto",
      "popa",
      "casco",
    ],
  },
  1: {
    groups: [
      {
        number: 1,
        theme: "Áreas do direito",
        words: ["civil", "penal", "tributário", "comercial"],
      },
      {
        number: 2,
        theme: "Engenharias",
        words: ["elétrica", "computação", "química", "produção"],
      },
      {
        number: 3,
        theme: "Sinônimos de produção",
        words: ["fabricação", "manufatura", "confecção", "montagem"],
      },
      {
        number: 4,
        theme: "Setores de uma empresa",
        words: ["recursos humanos", "financeiro", "suprimentos", "jurídico"],
      },
    ],
    startingBoard: [
      "suprimentos",
      "produção",
      "elétrica",
      "tributário",
      "comercial",
      "recursos humanos",
      "montagem",
      "penal",
      "manufatura",
      "jurídico",
      "financeiro",
      "confecção",
      "computação",
      "civil",
      "química",
      "fabricação",
    ],
  },
  2: {
    groups: [
      {
        number: 1,
        theme: "Nomes diferentes para a mesma coisa",
        words: ["mandioca", "macaxeira", "aipim", "maniva"],
      },
      {
        number: 2,
        theme: "Tipos de farinha",
        words: ["trigo", "milho", "aveia", "rosca"],
      },
      {
        number: 3,
        theme: "Típicos em festa junina",
        words: ["paçoca", "pamonha", "canjica", "pé de moleque"],
      },
      {
        number: 4,
        theme: "Insultos",
        words: ["banana", "galinha", "pão-duro", "cachorro"],
      },
    ],
    startingBoard: [
      "rosca",
      "pão-duro",
      "cachorro",
      "aipim",
      "milho",
      "canjica",
      "pé de moleque",
      "mandioca",
      "aveia",
      "galinha",
      "banana",
      "paçoca",
      "maniva",
      "pamonha",
      "macaxeira",
      "trigo",
    ],
  },
  3: {
    groups: [
      {
        number: 1,
        theme: "Clima",
        words: ["temperatura", "umidade", "precipitação", "vento"],
      },
      {
        number: 2,
        theme: "Exige rapidez",
        words: ["pressão", "urgência", "avidez", "impaciência"],
      },
      {
        number: 3,
        theme: "Turnos de trabalho",
        words: ["matutino", "vespertino", "integral", "plantão"],
      },
      {
        number: 4,
        theme: "Personagens de X-men",
        words: ["tempestade", "fera", "noturno", "mercúrio"],
      },
    ],
    startingBoard: [
      "urgência",
      "noturno",
      "impaciência",
      "plantão",
      "vespertino",
      "temperatura",
      "vento",
      "fera",
      "matutino",
      "precipitação",
      "mercúrio",
      "tempestade",
      "integral",
      "pressão",
      "avidez",
      "umidade",
    ],
  },
  4: {
    groups: [
      {
        number: 1,
        theme: "Astronomia",
        words: ["estrela", "órbita", "cinturão", "satélite"],
      },
      {
        number: 2,
        theme: "Continentes",
        words: ["áfrica", "ásia", "europa", "oceania"],
      },
      {
        number: 3,
        theme: "Eventos da vida",
        words: ["formatura", "casamento", "aposentadoria", "morte"],
      },
      {
        number: 4,
        theme: "Capitão ___",
        words: ["gancho", "planeta", "américa", "nascimento"],
      },
    ],
    startingBoard: [
      "órbita",
      "oceania",
      "formatura",
      "gancho",
      "ásia",
      "satélite",
      "américa",
      "europa",
      "casamento",
      "planeta",
      "cinturão",
      "nascimento",
      "morte",
      "aposentadoria",
      "estrela",
      "áfrica",
    ],
  },
  5: {
    groups: [
      {
        number: 1,
        theme: "Sinônimos de comer",
        words: ["alimenta", "degusta", "devora", "ingere"],
      },
      {
        number: 2,
        theme: "Veículos aquáticos",
        words: ["lancha", "submarino", "balsa", "veleiro"],
      },
      {
        number: 3,
        theme: "Times de futebol",
        words: ["cruzeiro", "atlético", "santos", "internacional"],
      },
      {
        number: 4,
        theme: "Viagem de avião",
        words: ["direto", "doméstico", "escala", "conexão"],
      },
    ],
    startingBoard: [
      "balsa",
      "cruzeiro",
      "internacional",
      "lancha",
      "devora",
      "doméstico",
      "conexão",
      "ingere",
      "santos",
      "direto",
      "submarino",
      "degusta",
      "veleiro",
      "escala",
      "alimenta",
      "atlético",
    ],
  },
  6: {
    groups: [
      {
        number: 1,
        theme: "Tem no celular",
        words: ["calendário", "agenda", "câmeras", "microfone"],
      },
      {
        number: 2,
        theme: "Acessórios de armazenamento",
        words: ["bolsas", "pochetes", "mochilas", "estojos"],
      },
      {
        number: 3,
        theme: "Usados para identificação",
        words: ["digitais", "face", "senhas", "assinaturas"],
      },
      {
        number: 4,
        theme: "Porta-___",
        words: ["retrato", "copos", "malas", "voz"],
      },
    ],
    startingBoard: [
      "assinaturas",
      "bolsas",
      "pochetes",
      "mochilas",
      "microfone",
      "voz",
      "face",
      "calendário",
      "estojos",
      "agenda",
      "senhas",
      "digitais",
      "malas",
      "copos",
      "câmeras",
      "retrato",
    ],
  },
  7: {
    groups: [
      {
        number: 1,
        theme: "Raças de cachorro",
        words: ["labrador", "poodle", "pastor", "boxer"],
      },
      {
        number: 2,
        theme: "Roupas íntimas",
        words: ["boxer", "sutiã", "calcinha", "ceroula"],
      },
      {
        number: 3,
        theme: "Estilos de música",
        words: ["samba", "sertanejo", "pagode", "brega"],
      },
      {
        number: 4,
        theme: "Sinônimos de música",
        words: ["canção", "cantiga", "toada", "moda"],
      },
    ],
    startingBoard: [
      "poodle",
      "samba",
      "calcinha",
      "toada",
      "boxer",
      "labrador",
      "canção",
      "brega",
      "pagode",
      "cantiga",
      "moda",
      "pastor",
      "ceroula",
      "sutiã",
      "boxer",
      "sertanejo",
    ],
  },
  8: {
    groups: [
      {
        number: 1,
        theme: "Não são animais",
        words: ["cogumelo", "bactéria", "protozoário", "alga"],
      },
      {
        number: 2,
        theme: "Animais domesticados",
        words: ["cachorro", "gato", "vaca", "porco"],
      },
      {
        number: 3,
        theme: "Frutos do mar",
        words: ["camarão", "lagosta", "caranguejo", "ostra"],
      },
      {
        number: 4,
        theme: "Animais relacionados a super-heróis",
        words: ["morcego", "aranha", "pantera", "formiga"],
      },
    ],
    startingBoard: [
      "bactéria",
      "morcego",
      "aranha",
      "alga",
      "vaca",
      "gato",
      "caranguejo",
      "cachorro",
      "cogumelo",
      "camarão",
      "formiga",
      "pantera",
      "protozoário",
      "lagosta",
      "porco",
      "ostra",
    ],
  },
};

export const useData = () => {
  return data;
};
