const data = {
  0: {
    groups: [
      {
        number: 1,
        theme: "Ditado popular",
        words: ["deus", "ajuda", "cedo", "madruga"],
      },
      {
        number: 2,
        theme: "Essenciais ao sair de casa",
        words: ["chaves", "celular", "carteira", "documento"],
      },
      {
        number: 3,
        theme: "Personagens de Chaves",
        words: ["chiquinha", "florinda", "nhonho", "quico"],
      },
      {
        number: 4,
        theme: "Profissões",
        words: ["professor", "advogado", "engenheiro", "policial"],
      },
    ],
    startingBoard: [
      "deus",
      "florinda",
      "policial",
      "carteira",
      "engenheiro",
      "chiquinha",
      "advogado",
      "cedo",
      "chaves",
      "celular",
      "quico",
      "documento",
      "professor",
      "madruga",
      "ajuda",
      "nhonho",
    ],
  },
  1: {
    groups: [
      {
        number: 1,
        theme: "Tipos de Pokémon",
        words: ["dragão", "fada", "psíquico", "elétrico"],
      },
      {
        number: 2,
        theme: "Títulos de nobreza",
        words: ["princesa", "duquesa", "baronesa", "condessa"],
      },
      {
        number: 3,
        theme: "Cartas de baralho representadas por letras",
        words: ["rei", "rainha", "valete", "ás"],
      },
      {
        number: 4,
        theme: "Categorias de fogão",
        words: ["gás", "indução", "cooktop", "lenha"],
      },
    ],
    startingBoard: [
      "indução",
      "princesa",
      "ás",
      "condessa",
      "psíquico",
      "rei",
      "duquesa",
      "cooktop",
      "gás",
      "elétrico",
      "dragão",
      "rainha",
      "valete",
      "baronesa",
      "lenha",
      "fada",
    ],
  },
  2: {
    groups: [
      {
        number: 1,
        theme: "Papel ___",
        words: ["alumínio", "toalha", "moeda", "celofane"],
      },
      {
        number: 2,
        theme: "Metais",
        words: ["estanho", "chumbo", "cobre", "zinco"],
      },
      {
        number: 3,
        theme: "Tem no banheiro",
        words: ["saboneteira", "banheira", "chuveiro", "espelho"],
      },
      {
        number: 4,
        theme: "Ossos do corpo humano",
        words: ["bacia", "clavícula", "fêmur", "tíbia"],
      },
    ],
    startingBoard: [
      "chumbo",
      "chuveiro",
      "estanho",
      "toalha",
      "espelho",
      "alumínio",
      "cobre",
      "moeda",
      "banheira",
      "tíbia",
      "saboneteira",
      "zinco",
      "clavícula",
      "celofane",
      "bacia",
      "fêmur",
    ],
  },
  3: {
    groups: [
      {
        number: 1,
        theme: "Personagens de Futurama",
        words: ["humano", "robô", "ciclope", "lagosta"],
      },
      {
        number: 2,
        theme: "Frutos do mar",
        words: ["lula", "siri", "vieira", "ostra"],
      },
      {
        number: 3,
        theme: "Árvores",
        words: ["oliveira", "pereira", "figueira", "macieira"],
      },
      {
        number: 4,
        theme: "Itens de limpeza",
        words: ["esponja", "balde", "flanela", "espanador"],
      },
    ],
    startingBoard: [
      "esponja",
      "siri",
      "oliveira",
      "figueira",
      "ciclope",
      "lula",
      "balde",
      "robô",
      "pereira",
      "macieira",
      "lagosta",
      "flanela",
      "vieira",
      "ostra",
      "espanador",
      "humano",
    ],
  },
  4: {
    groups: [
      {
        number: 1,
        theme: "Música",
        words: ["melodia", "ritmo", "harmonia", "tom"],
      },
      {
        number: 2,
        theme: "Felinos de desenhos animados",
        words: ["félix", "garfield", "frajola", "pacato"],
      },
      {
        number: 3,
        theme: "Tranquilo",
        words: ["sossegado", "calmo", "sereno", "plácido"],
      },
      {
        number: 4,
        theme: "Precipitação leve",
        words: ["garoa", "orvalho", "chuvisco", "neblina"],
      },
    ],
    startingBoard: [
      "garoa",
      "tom",
      "chuvisco",
      "sossegado",
      "ritmo",
      "plácido",
      "sereno",
      "orvalho",
      "calmo",
      "garfield",
      "melodia",
      "pacato",
      "neblina",
      "frajola",
      "harmonia",
      "félix",
    ],
  },
  5: {
    groups: [
      {
        number: 1,
        theme: "Os(as) sete ___",
        words: ["maravilhas", "pecados", "horcruxes", "anões"],
      },
      {
        number: 2,
        theme: "Objetos 3D",
        words: ["esferas", "cubos", "cones", "cilindros"],
      },
      {
        number: 3,
        theme: "Medidas de tempo",
        words: ["minutos", "séculos", "horas", "triênios"],
      },
      {
        number: 4,
        theme: "Nascem em cachos",
        words: ["uvas", "bananas", "mirtilos", "guaranás"],
      },
    ],
    startingBoard: [
      "horas",
      "esferas",
      "horcruxes",
      "anões",
      "triênios",
      "cilindros",
      "mirtilos",
      "cones",
      "bananas",
      "maravilhas",
      "séculos",
      "pecados",
      "minutos",
      "guaranás",
      "uvas",
      "cubos",
    ],
  },
  6: {
    groups: [
      {
        number: 1,
        theme: "Óleos vegetais",
        words: ["soja", "granola", "linhaça", "girassol"],
      },
      {
        number: 2,
        theme: "___ verde",
        words: ["cheiro", "chá ", "maçã ", "sinal"],
      },
      {
        number: 3,
        theme: "Grãos ",
        words: ["milho", "arroz", "ervilha", "lentilha"],
      },
      {
        number: 4,
        theme: "Flores do campo",
        words: ["cravo", "lírio", "gérbera", "tulipa"],
      },
    ],
    startingBoard: [
      "cheiro",
      "linhaça",
      "tulipa",
      "chá ",
      "granola",
      "lentilha",
      "girassol",
      "sinal",
      "lírio",
      "milho",
      "gérbera",
      "arroz",
      "ervilha",
      "cravo",
      "maçã ",
      "soja",
    ],
  },
  7: {
    groups: [
      {
        number: 1,
        theme: "Personagens de Irmão do Jorel",
        words: ["jorel", "lara", "nico", "juju"],
      },
      {
        number: 2,
        theme: "Pratos à base de feijão",
        words: ["feijoada", "acarajé", "tutu", "tropeiro"],
      },
      {
        number: 3,
        theme: "Pássaros de penugem preta",
        words: ["corvo", "anu", "graúna", "urubu"],
      },
      {
        number: 4,
        theme: "Mascotes de times de futebol",
        words: ["porco", "peixe", "galo", "raposa"],
      },
    ],
    startingBoard: [
      "galo",
      "graúna",
      "lara",
      "urubu",
      "porco",
      "tutu",
      "jorel",
      "corvo",
      "juju",
      "nico",
      "feijoada",
      "raposa",
      "tropeiro",
      "peixe",
      "acarajé",
      "anu",
    ],
  },
  8: {
    groups: [
      {
        number: 1,
        theme: "Internet",
        words: ["e-mail", "website", "download", "stream"],
      },
      {
        number: 2,
        theme: "Personagens que usam verde",
        words: ["luigi", "docinho", "cebolinha", "link"],
      },
      {
        number: 3,
        theme: "Temperos",
        words: ["orégano", "sálvia", "coentro", "tomilho"],
      },
      {
        number: 4,
        theme: "Meios de comunicação obsoletos",
        words: ["carta", "telegrama", "fax", "bip"],
      },
    ],
    startingBoard: [
      "telegrama",
      "bip",
      "cebolinha",
      "coentro",
      "luigi",
      "e-mail",
      "docinho",
      "carta",
      "link",
      "tomilho",
      "download",
      "fax",
      "website",
      "sálvia",
      "stream",
      "orégano",
    ],
  },
  9: {
    groups: [
      {
        number: 1,
        theme: "Itens de papelaria",
        words: ["diário", "agenda", "planner", "bloco"],
      },
      {
        number: 2,
        theme: "Adjetivos relativos a frequência",
        words: ["mensal", "anual", "semestral", "semanal"],
      },
      {
        number: 3,
        theme: "Carnaval",
        words: ["baile", "máscara", "escola", "marchinha"],
      },
      {
        number: 4,
        theme: "Cosméticos labiais",
        words: ["batom", "gloss", "tint", "bálsamo"],
      },
    ],
    startingBoard: [
      "semanal",
      "planner",
      "gloss",
      "tint",
      "semestral",
      "batom",
      "marchinha",
      "diário",
      "agenda",
      "anual",
      "bloco",
      "bálsamo",
      "escola",
      "mensal",
      "baile",
      "máscara",
    ],
  },
  10: {
    groups: [
      {
        number: 1,
        theme: "Roda (de) ___",
        words: ["moinho", "samba", "conversa", "gigante"],
      },
      {
        number: 2,
        theme: "Ritmos musicais",
        words: ["frevo", "axé", "bossa", "pagode"],
      },
      {
        number: 3,
        theme: "Enorme",
        words: ["imenso", "colossal", "titânico", "monumental"],
      },
      {
        number: 4,
        theme: "Clássicos literários",
        words: ["frankenstein ", "dom quixote", "metropolis", "drácula"],
      },
    ],
    startingBoard: [
      "pagode",
      "dom quixote",
      "imenso",
      "samba",
      "axé",
      "moinho",
      "colossal",
      "bossa",
      "metropolis",
      "monumental",
      "gigante",
      "titânico",
      "conversa",
      "drácula",
      "frankenstein ",
      "frevo",
    ],
  },
  11: {
    groups: [
      {
        number: 1,
        theme: "Usados no jardim",
        words: ["mangueira", "regador", "pá", "tesoura"],
      },
      {
        number: 2,
        theme: "Funções de modelos",
        words: ["desfile", "book", "anúncio", "evento"],
      },
      {
        number: 3,
        theme: "Pássaros",
        words: ["beija-flor", "canário", "sabiá", "rouxinol"],
      },
      {
        number: 4,
        theme: "Inteligente",
        words: ["perspicaz", "esperta", "astuta", "hábil"],
      },
    ],
    startingBoard: [
      "tesoura",
      "astuta",
      "sabiá",
      "beija-flor",
      "book",
      "regador",
      "evento",
      "mangueira",
      "hábil",
      "anúncio",
      "esperta",
      "perspicaz",
      "canário",
      "rouxinol",
      "desfile",
      "pá",
    ],
  },
  12: {
    groups: [
      {
        number: 1,
        theme: "Olívias famosas",
        words: ["rodrigo", "palito", "benson", "newton-john"],
      },
      {
        number: 2,
        theme: "Apóstolos",
        words: ["tiago", "simão", "andré", "pedro"],
      },
      {
        number: 3,
        theme: "Sobremesas geladas",
        words: ["sorvete", "picolé", "shake", "açaí"],
      },
      {
        number: 4,
        theme: "Típicos do Rio Grande do Sul",
        words: ["churrasco", "chimarrão", "bombacha", "carreteiro"],
      },
    ],
    startingBoard: [
      "sorvete",
      "picolé",
      "newton-john",
      "churrasco",
      "palito",
      "benson",
      "bombacha",
      "açaí",
      "andré",
      "chimarrão",
      "simão",
      "shake",
      "pedro",
      "rodrigo",
      "tiago",
      "carreteiro",
    ],
  },
  13: {
    groups: [
      {
        number: 1,
        theme: "Critérios para apuração do carnaval",
        words: ["bateria", "comissão", "evolução", "harmonia"],
      },
      {
        number: 2,
        theme: "Instrumentos musicais",
        words: ["tambor", "flauta", "cravo", "triângulo"],
      },
      {
        number: 3,
        theme: "Marsupiais",
        words: ["cuíca", "vombate", "coala", "diabo"],
      },
      {
        number: 4,
        theme: "Especiarias",
        words: ["canela", "cúrcuma", "zimbro", "cardamomo"],
      },
    ],
    startingBoard: [
      "triângulo",
      "bateria",
      "flauta",
      "coala",
      "tambor",
      "canela",
      "comissão",
      "cúrcuma",
      "evolução",
      "vombate",
      "cravo",
      "cuíca",
      "diabo",
      "cardamomo",
      "zimbro",
      "harmonia",
    ],
  },
  14: {
    groups: [
      {
        number: 1,
        theme: "Ratos de desenhos animados",
        words: ["comichão", "mickey", "cérebro", "jerry"],
      },
      {
        number: 2,
        theme: "Órgãos do corpo humano",
        words: ["pele", "fígado", "coração", "estômago"],
      },
      {
        number: 3,
        theme: "Reações comuns a picadas de insetos",
        words: ["alergia", "irritação", "inflamação", "coceira"],
      },
      {
        number: 4,
        theme: "Relacionados a sons",
        words: ["frequência", "timbre", "tom", "volume"],
      },
    ],
    startingBoard: [
      "cérebro",
      "frequência",
      "estômago",
      "mickey",
      "alergia",
      "timbre",
      "inflamação",
      "volume",
      "coceira",
      "pele",
      "irritação",
      "tom",
      "comichão",
      "coração",
      "jerry",
      "fígado",
    ],
  },
  15: {
    groups: [
      {
        number: 1,
        theme: "Os/As três ___",
        words: ["espiãs", "patetas", "porquinhos", "marias"],
      },
      {
        number: 2,
        theme: "Quadrinhos",
        words: ["mangás", "gibis", "almanaques", "revistinhas"],
      },
      {
        number: 3,
        theme: "Procedimentos policiais",
        words: ["revistas", "fiscalizações", "abordagens", "operações"],
      },
      {
        number: 4,
        theme: "Realizados no hospital",
        words: ["cirurgias", "exames", "hemodiálises", "transplantes"],
      },
    ],
    startingBoard: [
      "mangás",
      "espiãs",
      "transplantes",
      "operações",
      "porquinhos",
      "almanaques",
      "revistas",
      "patetas",
      "revistinhas",
      "abordagens",
      "gibis",
      "exames",
      "cirurgias",
      "marias",
      "hemodiálises",
      "fiscalizações",
    ],
  },
  16: {
    groups: [
      {
        number: 1,
        theme: "Variedades de bananas",
        words: ["nanica", "maçã", "plantain", "prata"],
      },
      {
        number: 2,
        theme: "Planetas",
        words: ["terra", "marte", "vênus", "saturno"],
      },
      {
        number: 3,
        theme: "Mitologia grega",
        words: ["afrodite", "zeus", "atena", "hades"],
      },
      {
        number: 4,
        theme: "Filmes da Disney",
        words: ["hércules", "dálmatas", "corcunda", "pinóquio"],
      },
    ],
    startingBoard: [
      "afrodite",
      "prata",
      "hades",
      "plantain",
      "vênus",
      "maçã",
      "dálmatas",
      "marte",
      "atena",
      "terra",
      "nanica",
      "corcunda",
      "zeus",
      "hércules",
      "pinóquio",
      "saturno",
    ],
  },
  17: {
    groups: [
      {
        number: 1,
        theme: "Direitos humanos",
        words: ["vida", "liberdade", "igualdade", "segurança"],
      },
      {
        number: 2,
        theme: "Bairros de São Paulo",
        words: ["pinheiros", "mooca", "ipiranga", "jardins"],
      },
      {
        number: 3,
        theme: "Árvores",
        words: ["eucaliptos", "carvalhos", "jatobás", "ipês"],
      },
      {
        number: 4,
        theme: "Sinônimos de exposição",
        words: ["feira", "mostra", "apresentação", "exibição"],
      },
    ],
    startingBoard: [
      "jatobás",
      "ipiranga",
      "ipês",
      "mostra",
      "segurança",
      "eucaliptos",
      "liberdade",
      "jardins",
      "igualdade",
      "mooca",
      "feira",
      "carvalhos",
      "exibição",
      "apresentação",
      "vida",
      "pinheiros",
    ],
  },
  18: {
    groups: [
      {
        number: 1,
        theme: "Levamos para a praia",
        words: ["cadeira", "protetor", "sombrinha", "óculos"],
      },
      {
        number: 2,
        theme: "Guardião",
        words: ["zelador", "tutor", "custódio", "conservador"],
      },
      {
        number: 3,
        theme: "Cargos numa escola",
        words: ["professor", "supervisor", "diretor", "tesoureiro"],
      },
      {
        number: 4,
        theme: "Quebra-___",
        words: ["galho", "nozes", "cabeça", "molas"],
      },
    ],
    startingBoard: [
      "custódio",
      "tesoureiro",
      "professor",
      "molas",
      "diretor",
      "galho",
      "óculos",
      "cabeça",
      "conservador",
      "nozes",
      "zelador",
      "sombrinha",
      "tutor",
      "cadeira",
      "supervisor",
      "protetor",
    ],
  },
  19: {
    groups: [
      {
        number: 1,
        theme: "Emite sons de animais",
        words: ["pia", "late", "muge", "uiva"],
      },
      {
        number: 2,
        theme: "Letras gregas",
        words: ["alfa", "beta", "gama", "lambda"],
      },
      {
        number: 3,
        theme: "Peixes de aquário",
        words: ["zebra", "palhaço", "cascudo", "anjo"],
      },
      {
        number: 4,
        theme: "Personagens de Pulp Fiction",
        words: ["mia", "jules", "vincent", "zed"],
      },
    ],
    startingBoard: [
      "vincent",
      "cascudo",
      "alfa",
      "beta",
      "anjo",
      "late",
      "uiva",
      "jules",
      "muge",
      "zed",
      "palhaço",
      "pia",
      "gama",
      "lambda",
      "mia",
      "zebra",
    ],
  },
  20: {
    groups: [
      {
        number: 1,
        theme: "Cães de desenhos animados",
        words: ["scooby", "coragem", "ajudante", "brian"],
      },
      {
        number: 2,
        theme: "Cargos auxiliares",
        words: ["secretário", "assistente", "assessor", "colaborador"],
      },
      {
        number: 3,
        theme: "Tubérculos",
        words: ["mandioca", "cará", "batata", "inhame"],
      },
      {
        number: 4,
        theme: "Indumentária real",
        words: ["túnica", "manto", "coroa", "cedro"],
      },
    ],
    startingBoard: [
      "brian",
      "coroa",
      "túnica",
      "scooby",
      "secretário",
      "mandioca",
      "assessor",
      "batata",
      "manto",
      "colaborador",
      "ajudante",
      "coragem",
      "inhame",
      "assistente",
      "cedro",
      "cará",
    ],
  },
  21: {
    groups: [
      {
        number: 1,
        theme: "Que tem boa saúde",
        words: ["sadia", "sã", "forte", "saudável"],
      },
      {
        number: 2,
        theme: "Marcas de alimentos",
        words: ["nestlé", "pifpaf", "seara", "perdigão"],
      },
      {
        number: 3,
        theme: "Jogos de baralho",
        words: ["buraco", "paciência", "truco", "poker"],
      },
      {
        number: 4,
        theme: "Calma",
        words: ["pacatez", "tranquilidade", "serenidade", "mansidão"],
      },
    ],
    startingBoard: [
      "tranquilidade",
      "paciência",
      "perdigão",
      "truco",
      "buraco",
      "sã",
      "saudável",
      "nestlé",
      "forte",
      "serenidade",
      "seara",
      "sadia",
      "poker",
      "mansidão",
      "pifpaf",
      "pacatez",
    ],
  },
  22: {
    groups: [
      {
        number: 1,
        theme: "Notas musicais",
        words: ["dó", "mi", "si", "fá"],
      },
      {
        number: 2,
        theme: "Fontes de energia",
        words: ["vento", "sol", "carvão", "água"],
      },
      {
        number: 3,
        theme: "Advérbios de lugar",
        words: ["lá", "ali", "aqui", "acolá"],
      },
      {
        number: 4,
        theme: "Participantes num processo judicial",
        words: ["ré", "juíza", "testemunha", "autora"],
      },
    ],
    startingBoard: [
      "água",
      "autora",
      "dó",
      "ali",
      "ré",
      "carvão",
      "juíza",
      "fá",
      "sol",
      "aqui",
      "testemunha",
      "acolá",
      "vento",
      "mi",
      "lá",
      "si",
    ],
  },
  23: {
    groups: [
      {
        number: 1,
        theme: "Supermercado",
        words: ["corredor", "prateleira", "caixa", "carrinho"],
      },
      {
        number: 2,
        theme: "Brinquedos",
        words: ["bola", "boneca", "pipa", "pelúcia"],
      },
      {
        number: 3,
        theme: "Usados para armazenamento",
        words: ["cesto", "baú", "gaveta", "mala"],
      },
      {
        number: 4,
        theme: "Móveis",
        words: ["estante", "sofá", "cadeira", "mesa"],
      },
    ],
    startingBoard: [
      "carrinho",
      "cesto",
      "caixa",
      "corredor",
      "cadeira",
      "boneca",
      "gaveta",
      "sofá",
      "bola",
      "mesa",
      "mala",
      "prateleira",
      "pelúcia",
      "baú",
      "pipa",
      "estante",
    ],
  },
  24: {
    groups: [
      {
        number: 1,
        theme: "Marcas de biscoito recheado",
        words: ["bono", "passatempo", "negresco", "aymoré"],
      },
      {
        number: 2,
        theme: "Travesso",
        words: ["traquinas", "arteiro", "inquieto", "levado"],
      },
      {
        number: 3,
        theme: "Diversão",
        words: ["lazer", "distração", "brincadeira", "entretenimento"],
      },
      {
        number: 4,
        theme: "Guarda-___",
        words: ["sol", "chuva", "roupa", "costas"],
      },
    ],
    startingBoard: [
      "sol",
      "brincadeira",
      "costas",
      "bono",
      "inquieto",
      "negresco",
      "distração",
      "levado",
      "passatempo",
      "arteiro",
      "traquinas",
      "chuva",
      "lazer",
      "aymoré",
      "roupa",
      "entretenimento",
    ],
  },
  25: {
    groups: [
      {
        number: 1,
        theme: "Operações matemáticas",
        words: ["subtração", "adição", "multiplicação", "divisão"],
      },
      {
        number: 2,
        theme: "Eficiência",
        words: ["poder", "força", "vigor", "potência"],
      },
      {
        number: 3,
        theme: "Tons de azul",
        words: ["cobalto", "bebê", "petróleo", "celeste"],
      },
      {
        number: 4,
        theme: "Origem",
        words: ["raiz", "princípio", "fonte", "fundamento"],
      },
    ],
    startingBoard: [
      "poder",
      "bebê",
      "raiz",
      "subtração",
      "vigor",
      "fonte",
      "cobalto",
      "divisão",
      "fundamento",
      "potência",
      "adição",
      "petróleo",
      "princípio",
      "multiplicação",
      "força",
      "celeste",
    ],
  },
  26: {
    groups: [
      {
        number: 1,
        theme: "Para armazenar ou servir alimentos",
        words: ["tigela", "pote", "prato", "travessa"],
      },
      {
        number: 2,
        theme: "Partes de uma bateria",
        words: ["caixa", "bumbo", "surdo", "baqueta"],
      },
      {
        number: 3,
        theme: "Vias públicas",
        words: ["rua", "avenida", "alameda", "beco"],
      },
      {
        number: 4,
        theme: "Bancos",
        words: ["nu", "inter", "brasil", "bradesco"],
      },
    ],
    startingBoard: [
      "inter",
      "avenida",
      "caixa",
      "bradesco",
      "travessa",
      "tigela",
      "rua",
      "prato",
      "brasil",
      "baqueta",
      "alameda",
      "surdo",
      "beco",
      "pote",
      "nu",
      "bumbo",
    ],
  },
  27: {
    groups: [
      {
        number: 1,
        theme: "Partes do dente",
        words: ["coroa", "esmalte", "raiz", "osso"],
      },
      {
        number: 2,
        theme: "Cosméticos",
        words: ["batom", "perfume", "hidratante", "delineador"],
      },
      {
        number: 3,
        theme: "Usa-se na cabeça",
        words: ["tiara", "laço", "chapéu", "bandana"],
      },
      {
        number: 4,
        theme: "___ de/do amor",
        words: ["serenata", "carta", "maçã", "declaração"],
      },
    ],
    startingBoard: [
      "raiz",
      "tiara",
      "coroa",
      "bandana",
      "osso",
      "chapéu",
      "carta",
      "esmalte",
      "batom",
      "serenata",
      "perfume",
      "maçã",
      "delineador",
      "declaração",
      "laço",
      "hidratante",
    ],
  },
  28: {
    groups: [
      {
        number: 1,
        theme: "Estabeleça comunicação",
        words: ["converse", "interaja", "papeie", "dialogue"],
      },
      {
        number: 2,
        theme: "Marcas de calçados",
        words: ["nike", "adidas", "vans", "rainha"],
      },
      {
        number: 3,
        theme: "Felinos selvagens",
        words: ["puma", "leopardo", "jaguar", "lince"],
      },
      {
        number: 4,
        theme: "Meios de transporte de carga",
        words: ["caminhões", "furgões", "carretas", "trens"],
      },
    ],
    startingBoard: [
      "puma",
      "trens",
      "vans",
      "furgões",
      "adidas",
      "papeie",
      "lince",
      "converse",
      "nike",
      "jaguar",
      "carretas",
      "rainha",
      "caminhões",
      "leopardo",
      "dialogue",
      "interaja",
    ],
  },
  30: {
    groups: [
      {
        number: 1,
        theme: "Cores naturais de cabelos",
        words: ["ruivo", "caramelo", "castanho", "preto"],
      },
      {
        number: 2,
        theme: "Temperos",
        words: ["louro", "canela", "sálvia", "gengibre"],
      },
      {
        number: 3,
        theme: "Hortaliças",
        words: ["brócolis", "hortelã", "quiabo", "rabanete"],
      },
      {
        number: 4,
        theme: "Partes da perna",
        words: ["tornozelo", "batata", "coxa", "joelho"],
      },
    ],
    startingBoard: [
      "caramelo",
      "batata",
      "castanho",
      "ruivo",
      "brócolis",
      "sálvia",
      "hortelã",
      "joelho",
      "gengibre",
      "rabanete",
      "preto",
      "quiabo",
      "louro",
      "coxa",
      "canela",
      "tornozelo",
    ],
  },
};

export const useData = () => {
  return data;
};
