const data = {
  0: {
    groups: [
      {
        number: 1,
        theme: "Música",
        words: ["acorde", "harmonia", "ritmo", "melodia"],
      },
      {
        number: 2,
        theme: "Formas de pagamento",
        words: ["nota", "moeda", "cartão", "pix"],
      },
      {
        number: 3,
        theme: "Objetos de sentar",
        words: ["banco", "pufe", "sofá", "cadeira"],
      },
      {
        number: 4,
        theme: "Coisas de escola",
        words: ["histórico", "boletim", "prova", "trabalho"],
      },
    ],
    startingBoard: [
      "nota",
      "cadeira",
      "banco",
      "prova",
      "pufe",
      "ritmo",
      "boletim",
      "moeda",
      "sofá",
      "harmonia",
      "trabalho",
      "melodia",
      "cartão",
      "histórico",
      "acorde",
      "pix",
    ],
  },
  1: {
    groups: [
      {
        number: 1,
        theme: "Materiais de construção",
        words: ["cimento", "tijolo", "areia", "pedra"],
      },
      {
        number: 2,
        theme: "Elementos químicos",
        words: ["ferro", "oxigênio", "carbono", "flúor"],
      },
      {
        number: 3,
        theme: "Fogo",
        words: ["fósforo", "isqueiro", "vela", "lampião"],
      },
      {
        number: 4,
        theme: "Esportes aquáticos",
        words: ["surfe", "remo", "natação", "canoagem"],
      },
    ],
    startingBoard: [
      "ferro",
      "cimento",
      "carbono",
      "isqueiro",
      "lampião",
      "vela",
      "tijolo",
      "remo",
      "surfe",
      "areia",
      "oxigênio",
      "natação",
      "pedra",
      "fósforo",
      "flúor",
      "canoagem",
    ],
  },
  2: {
    groups: [
      {
        number: 1,
        theme: "Títulos de nobreza",
        words: ["príncipe", "duque", "marquês", "conde"],
      },
      {
        number: 2,
        theme: "Formas de governo",
        words: ["reino", "estado", "república", "principado"],
      },
      {
        number: 3,
        theme: "Classificação biológica",
        words: ["ordem", "espécie", "classe", "família"],
      },
      {
        number: 4,
        theme: "Títulos de Harry Potter",
        words: ["pedra", "câmara", "prisioneiro", "cálice"],
      },
    ],
    startingBoard: [
      "pedra",
      "prisioneiro",
      "marquês",
      "câmara",
      "ordem",
      "principado",
      "duque",
      "príncipe",
      "reino",
      "classe",
      "estado",
      "república",
      "conde",
      "família",
      "espécie",
      "cálice",
    ],
  },
  3: {
    groups: [
      {
        number: 1,
        theme: "Frutas tropicais",
        words: ["caju", "graviola", "cupuaçu", "lichia"],
      },
      {
        number: 2,
        theme: "Partes de roupa",
        words: ["manga", "botão", "gola", "cós"],
      },
      {
        number: 3,
        theme: "Formas de chocolate",
        words: ["barra", "calda", "ovo", "pó"],
      },
      {
        number: 4,
        theme: "Revestimentos",
        words: ["cobertura", "casca", "capa", "forro"],
      },
    ],
    startingBoard: [
      "botão",
      "pó",
      "manga",
      "lichia",
      "barra",
      "caju",
      "gola",
      "forro",
      "cupuaçu",
      "cós",
      "ovo",
      "capa",
      "cobertura",
      "calda",
      "graviola",
      "casca",
    ],
  },
  4: {
    groups: [
      {
        number: 1,
        theme: "Meios de transporte",
        words: ["condução", "coletivo", "lotação", "comboio"],
      },
      {
        number: 2,
        theme: "Ter o comando",
        words: ["domínio", "controle", "soberania", "posse"],
      },
      {
        number: 3,
        theme: "Partes de um hotel",
        words: ["recepção", "quarto", "corredor", "saguão"],
      },
      {
        number: 4,
        theme: "Fundamentos de futebol",
        words: ["cabeçada", "passe", "chute", "drible"],
      },
    ],
    startingBoard: [
      "chute",
      "domínio",
      "recepção",
      "condução",
      "corredor",
      "drible",
      "passe",
      "controle",
      "comboio",
      "posse",
      "coletivo",
      "cabeçada",
      "saguão",
      "lotação",
      "soberania",
      "quarto",
    ],
  },
  5: {
    groups: [
      {
        number: 1,
        theme: "Tarefas escolares",
        words: ["pergunta", "problema", "questão", "redação"],
      },
      {
        number: 2,
        theme: "Coisas de igreja",
        words: ["relicário", "órgão", "candelabro", "castiçal"],
      },
      {
        number: 3,
        theme: "Órgãos do corpo",
        words: ["rim", "fígado", "baço", "apêndice"],
      },
      {
        number: 4,
        theme: "Pode-se soprar",
        words: ["apito", "resposta", "vela", "bexiga"],
      },
    ],
    startingBoard: [
      "rim",
      "relicário",
      "apito",
      "pergunta",
      "fígado",
      "órgão",
      "resposta",
      "problema",
      "baço",
      "questão",
      "vela",
      "redação",
      "apêndice",
      "candelabro",
      "castiçal",
      "bexiga",
    ],
  },
  6: {
    groups: [
      {
        number: 1,
        theme: "Usados para limpeza",
        words: ["cloro", "água", "pá", "rodo"],
      },
      {
        number: 2,
        theme: "Muda de direção",
        words: ["roda", "vira", "gira", "volve"],
      },
      {
        number: 3,
        theme: "Partes de carro",
        words: ["mola", "eixo", "porta", "poltrona"],
      },
      {
        number: 4,
        theme: "Podem ser infláveis",
        words: ["colchão", "castelo", "colete", "piscina"],
      },
    ],
    startingBoard: [
      "mola",
      "roda",
      "colchão",
      "cloro",
      "eixo",
      "vira",
      "castelo",
      "água",
      "porta",
      "pá",
      "colete",
      "rodo",
      "poltrona",
      "piscina",
      "gira",
      "volve",
    ],
  },
  7: {
    groups: [
      {
        number: 1,
        theme: "Jogo de ___",
        words: ["mesa", "console", "celular", "computador"],
      },
      {
        number: 2,
        theme: "Objetos de casa",
        words: ["cadeira", "sofá", "cama", "fogão"],
      },
      {
        number: 3,
        theme: "Partes da casa",
        words: ["cozinha", "sala", "quarto", "banheiro"],
      },
      {
        number: 4,
        theme: "Conexões",
        words: ["internet", "wi-fi", "bluetooth", "infravermelho"],
      },
    ],
    startingBoard: [
      "console",
      "quarto",
      "bluetooth",
      "banheiro",
      "mesa",
      "cadeira",
      "sala",
      "internet",
      "celular",
      "computador",
      "infravermelho",
      "cozinha",
      "wi-fi",
      "sofá",
      "fogão",
      "cama",
    ],
  },
  8: {
    groups: [
      {
        number: 1,
        theme: "Mar ___",
        words: ["vermelho", "negro", "morto", "mediterrâneo"],
      },
      {
        number: 2,
        theme: "Flores",
        words: ["vaso", "buquê", "coroa", "arranjo"],
      },
      {
        number: 3,
        theme: "Feitos de madeira",
        words: ["caixão", "móveis", "tábua", "violão"],
      },
      {
        number: 4,
        theme: "Tipos de molho",
        words: ["verde", "rosê", "tomate", "tártaro"],
      },
    ],
    startingBoard: [
      "verde",
      "tártaro",
      "vermelho",
      "arranjo",
      "tomate",
      "violão",
      "mediterrâneo",
      "buquê",
      "móveis",
      "morto",
      "tábua",
      "negro",
      "rosê",
      "coroa",
      "vaso",
      "caixão",
    ],
  },
  9: {
    groups: [
      {
        number: 1,
        theme: "Filhotes de animais",
        words: ["larva", "leitão", "bezerro", "girino"],
      },
      {
        number: 2,
        theme: "Espécies de cobra",
        words: ["coral", "verde", "cascavel", "sucuri"],
      },
      {
        number: 3,
        theme: "Aves brasileiras",
        words: ["jacutinga", "bem-te-vi", "tucano", "sabiá"],
      },
      {
        number: 4,
        theme: "Palíndromos",
        words: ["reviver", "arara", "mirim", "anilina"],
      },
    ],
    startingBoard: [
      "sucuri",
      "coral",
      "reviver",
      "mirim",
      "sabiá",
      "tucano",
      "cascavel",
      "bem-te-vi",
      "arara",
      "leitão",
      "jacutinga",
      "girino",
      "verde",
      "anilina",
      "bezerro",
      "larva",
    ],
  },
  10: {
    groups: [
      {
        number: 1,
        theme: "Termos de geometria",
        words: ["ponto", "reta", "plano", "espaço"],
      },
      {
        number: 2,
        theme: "Transportes públicos",
        words: ["ônibus", "trem", "metrô", "bonde"],
      },
      {
        number: 3,
        theme: "Geografia urbana",
        words: ["rua", "bairro", "cidade", "endereço"],
      },
      {
        number: 4,
        theme: "Componentes de uma carta",
        words: ["remetente", "destinatário", "envelope", "selo"],
      },
    ],
    startingBoard: [
      "ponto",
      "endereço",
      "metrô",
      "plano",
      "selo",
      "espaço",
      "rua",
      "bairro",
      "destinatário",
      "cidade",
      "remetente",
      "ônibus",
      "bonde",
      "trem",
      "envelope",
      "reta",
    ],
  },
  11: {
    groups: [
      {
        number: 1,
        theme: "Alterações de fala/voz",
        words: ["gaga", "muda", "fanha", "rouca"],
      },
      {
        number: 2,
        theme: "Objetos astronômicos",
        words: ["estrela", "sol", "planeta", "satélite"],
      },
      {
        number: 3,
        theme: "Cantoras pop",
        words: ["perry", "spears", "j", "lovato"],
      },
      {
        number: 4,
        theme: "Linguagens de programação",
        words: ["lua", "c", "swift", "r"],
      },
    ],
    startingBoard: [
      "perry",
      "spears",
      "j",
      "rouca",
      "fanha",
      "satélite",
      "r",
      "planeta",
      "swift",
      "lua",
      "lovato",
      "sol",
      "muda",
      "estrela",
      "gaga",
      "c",
    ],
  },
  12: {
    groups: [
      {
        number: 1,
        theme: "Os 4 elementos",
        words: ["água", "terra", "fogo", "ar"],
      },
      {
        number: 2,
        theme: "Ambientes aquáticos",
        words: ["cachoeira", "rio", "mar", "lago"],
      },
      {
        number: 3,
        theme: "Tipos de carne",
        words: ["peixe", "frango", "boi", "cordeiro"],
      },
      {
        number: 4,
        theme: "Verbos",
        words: ["nadar", "cozinhar", "voar", "mergulhar"],
      },
    ],
    startingBoard: [
      "lago",
      "peixe",
      "cozinhar",
      "ar",
      "fogo",
      "mar",
      "nadar",
      "mergulhar",
      "boi",
      "frango",
      "cachoeira",
      "rio",
      "cordeiro",
      "terra",
      "voar",
      "água",
    ],
  },
  13: {
    groups: [
      {
        number: 1,
        theme: "Personagens de Chaves",
        words: ["chiquinha", "quico", "florinda", "girafales"],
      },
      {
        number: 2,
        theme: "Partes do corpo",
        words: ["barriga", "cabeça", "braço", "ombro"],
      },
      {
        number: 3,
        theme: "Relacionados ao litoral",
        words: ["costa", "orla", "praia", "baía"],
      },
      {
        number: 4,
        theme: "Estados do Nordeste",
        words: ["alagoas", "pernambuco", "ceará", "sergipe"],
      },
    ],
    startingBoard: [
      "braço",
      "pernambuco",
      "cabeça",
      "florinda",
      "girafales",
      "quico",
      "baía",
      "sergipe",
      "ceará",
      "alagoas",
      "praia",
      "barriga",
      "orla",
      "costa",
      "chiquinha",
      "ombro",
    ],
  },
  14: {
    groups: [
      {
        number: 1,
        theme: "Podem ter no bolo",
        words: ["glacê", "recheio", "calda", "cobertura"],
      },
      {
        number: 2,
        theme: "Conjunto de pessoas",
        words: ["massa", "público", "povo", "população"],
      },
      {
        number: 3,
        theme: "Algo legal ou positivo",
        words: ["show", "maneiro", "beleza", "jóia"],
      },
      {
        number: 4,
        theme: "Eventos de artistas",
        words: ["turnê", "festival", "concerto", "performance"],
      },
    ],
    startingBoard: [
      "massa",
      "glacê",
      "performance",
      "população",
      "jóia",
      "beleza",
      "povo",
      "festival",
      "calda",
      "turnê",
      "concerto",
      "maneiro",
      "show",
      "cobertura",
      "recheio",
      "público",
    ],
  },
  15: {
    groups: [
      {
        number: 1,
        theme: "Onomatopéias",
        words: ["zap", "tic-tac", "pocotó", "cocoricó"],
      },
      {
        number: 2,
        theme: "Vilões do Batman",
        words: ["coringa", "charada", "crocodilo", "pinguim"],
      },
      {
        number: 3,
        theme: "Jogos de cartas",
        words: ["buraco", "pife", "truco", "poker"],
      },
      {
        number: 4,
        theme: "Naipes de cartas",
        words: ["paus", "copas", "espadas", "ouros"],
      },
    ],
    startingBoard: [
      "crocodilo",
      "coringa",
      "cocoricó",
      "pocotó",
      "pife",
      "truco",
      "copas",
      "paus",
      "espadas",
      "charada",
      "buraco",
      "poker",
      "pinguim",
      "ouros",
      "tic-tac",
      "zap",
    ],
  },
  16: {
    groups: [
      {
        number: 1,
        theme: "Substantivos coletivos",
        words: ["clero", "álbum", "arquipélago", "enxame"],
      },
      {
        number: 2,
        theme: "Lugares em uma cidade",
        words: ["igreja", "hospital", "praça", "posto"],
      },
      {
        number: 3,
        theme: "Fotografia",
        words: ["foto", "paisagem", "retrato", "revelar"],
      },
      {
        number: 4,
        theme: "Abelhas",
        words: ["mel", "colméia", "rainha", "operária"],
      },
    ],
    startingBoard: [
      "álbum",
      "igreja",
      "clero",
      "rainha",
      "arquipélago",
      "enxame",
      "retrato",
      "colméia",
      "operária",
      "mel",
      "paisagem",
      "foto",
      "revelar",
      "praça",
      "hospital",
      "posto",
    ],
  },
  17: {
    groups: [
      {
        number: 1,
        theme: "Hierarquia militar",
        words: ["cabo", "soldado", "brigadeiro", "major"],
      },
      {
        number: 2,
        theme: "Doces",
        words: ["beijinho", "cajuzinho", "cocada", "casadinho"],
      },
      {
        number: 3,
        theme: "Bordado",
        words: ["fio", "linha", "agulha", "ponto"],
      },
      {
        number: 4,
        theme: "Frutas redondas",
        words: ["côco", "melão", "melancia", "laranja"],
      },
    ],
    startingBoard: [
      "linha",
      "laranja",
      "beijinho",
      "soldado",
      "casadinho",
      "melancia",
      "major",
      "cajuzinho",
      "fio",
      "cocada",
      "melão",
      "côco",
      "agulha",
      "brigadeiro",
      "ponto",
      "cabo",
    ],
  },
  18: {
    groups: [
      {
        number: 1,
        theme: "Partes de um texto",
        words: ["palavra", "sílaba", "frase", "parágrafo"],
      },
      {
        number: 2,
        theme: "Composição de música",
        words: ["letra", "melodia", "instrumento", "ritmo"],
      },
      {
        number: 3,
        theme: "Mídias impressas",
        words: ["livro", "revista", "quadrinhos", "jornal"],
      },
      {
        number: 4,
        theme: "Podem ser enviados pelo WhatsApp",
        words: ["foto", "vídeo", "áudio", "contato"],
      },
    ],
    startingBoard: [
      "contato",
      "palavra",
      "foto",
      "frase",
      "vídeo",
      "livro",
      "parágrafo",
      "ritmo",
      "instrumento",
      "áudio",
      "quadrinhos",
      "sílaba",
      "jornal",
      "letra",
      "revista",
      "melodia",
    ],
  },
  19: {
    groups: [
      {
        number: 1,
        theme: "Armas medievais",
        words: ["adaga", "maça", "escudo", "lança"],
      },
      {
        number: 2,
        theme: "Tipos de carro",
        words: ["híbrido", "conversível", "esportivo", "perua"],
      },
      {
        number: 3,
        theme: "Artistas de circo",
        words: ["mágico", "malabarista", "domador", "engolidor"],
      },
      {
        number: 4,
        theme: "Peixe-___",
        words: ["palhaço", "voador", "elétrico", "espada"],
      },
    ],
    startingBoard: [
      "espada",
      "adaga",
      "malabarista",
      "conversível",
      "palhaço",
      "maça",
      "mágico",
      "lança",
      "perua",
      "voador",
      "escudo",
      "híbrido",
      "domador",
      "engolidor",
      "esportivo",
      "elétrico",
    ],
  },
  20: {
    groups: [
      {
        number: 1,
        theme: "Animais de estimação",
        words: ["gato", "cachorro", "papagaio", "hamster"],
      },
      {
        number: 2,
        theme: "Meia-___",
        words: ["calça", "noite", "entrada", "dúzia"],
      },
      {
        number: 3,
        theme: "Tipos de roupa",
        words: ["polo", "cardigã", "shorts", "jaqueta"],
      },
      {
        number: 4,
        theme: "Trava-língua famoso",
        words: ["rato", "roupa", "rei", "roma"],
      },
    ],
    startingBoard: [
      "hamster",
      "noite",
      "dúzia",
      "rei",
      "shorts",
      "gato",
      "cardigã",
      "calça",
      "rato",
      "jaqueta",
      "entrada",
      "polo",
      "cachorro",
      "papagaio",
      "roupa",
      "roma",
    ],
  },
  21: {
    groups: [
      {
        number: 1,
        theme: "Tipos de comércio",
        words: ["mercado", "quitanda", "bazar", "boutique"],
      },
      {
        number: 2,
        theme: "Locais de armazenamento",
        words: ["depósito", "despensa", "armazém", "almoxarifado"],
      },
      {
        number: 3,
        theme: "Fundamentos do vôlei",
        words: ["saque", "bloqueio", "levantamento", "corte"],
      },
      {
        number: 4,
        theme: "Faz-se no banco",
        words: ["empréstimo", "financiamento", "pagamento", "investimento"],
      },
    ],
    startingBoard: [
      "levantamento",
      "boutique",
      "pagamento",
      "quitanda",
      "financiamento",
      "bloqueio",
      "investimento",
      "empréstimo",
      "armazém",
      "corte",
      "despensa",
      "almoxarifado",
      "mercado",
      "depósito",
      "bazar",
      "saque",
    ],
  },
  22: {
    groups: [
      {
        number: 1,
        theme: "Ações de culinária",
        words: ["cortar", "fatiar", "ralar", "misturar"],
      },
      {
        number: 2,
        theme: "Ações de animais",
        words: ["picar", "ruminar", "uivar", "rosnar"],
      },
      {
        number: 3,
        theme: "Atividades físicas",
        words: ["nadar", "pular", "saltar", "caminhar"],
      },
      {
        number: 4,
        theme: "Substantivos",
        words: ["altar", "caviar", "celular", "radar"],
      },
    ],
    startingBoard: [
      "picar",
      "nadar",
      "caviar",
      "pular",
      "rosnar",
      "cortar",
      "altar",
      "misturar",
      "fatiar",
      "ralar",
      "celular",
      "caminhar",
      "uivar",
      "radar",
      "ruminar",
      "saltar",
    ],
  },
  23: {
    groups: [
      {
        number: 1,
        theme: "Futebol",
        words: ["gol", "lateral", "escanteio", "pênalti"],
      },
      {
        number: 2,
        theme: "Tiro com arco",
        words: ["flecha", "arco", "corda", "tiro"],
      },
      {
        number: 3,
        theme: "Empresas de tecnologia",
        words: ["google", "amazon", "netflix", "cisco"],
      },
      {
        number: 4,
        theme: "Sinônimos de objetivo",
        words: ["alvo", "meta", "fim", "propósito"],
      },
    ],
    startingBoard: [
      "flecha",
      "corda",
      "amazon",
      "tiro",
      "fim",
      "arco",
      "escanteio",
      "lateral",
      "google",
      "alvo",
      "netflix",
      "cisco",
      "propósito",
      "pênalti",
      "gol",
      "meta",
    ],
  },
  24: {
    groups: [
      {
        number: 1,
        theme: "Cuidados para plantas",
        words: ["colher", "plantar", "regar", "cortar"],
      },
      {
        number: 2,
        theme: "Objetos com pontas",
        words: ["garfo", "palito", "alfinete", "agulha"],
      },
      {
        number: 3,
        theme: "Armas cortantes",
        words: ["faca", "espada", "machado", "canivete"],
      },
      {
        number: 4,
        theme: "Tem no jardim",
        words: ["mangueira", "flor", "planta", "cerca"],
      },
    ],
    startingBoard: [
      "alfinete",
      "regar",
      "garfo",
      "colher",
      "cortar",
      "espada",
      "cerca",
      "flor",
      "faca",
      "planta",
      "canivete",
      "plantar",
      "palito",
      "machado",
      "agulha",
      "mangueira",
    ],
  },
  25: {
    groups: [
      {
        number: 1,
        theme: "Ensino ___",
        words: ["superior", "fundamental", "médio", "técnico"],
      },
      {
        number: 2,
        theme: "Tipos de livro",
        words: ["infantil", "ficção", "biografia", "didático"],
      },
      {
        number: 3,
        theme: "Coisas que podemos medir",
        words: ["distância", "peso", "tempo", "temperatura"],
      },
      {
        number: 4,
        theme: "Objetos de medição",
        words: ["trena", "balança", "cronômetro", "termômetro"],
      },
    ],
    startingBoard: [
      "biografia",
      "peso",
      "cronômetro",
      "infantil",
      "médio",
      "superior",
      "termômetro",
      "ficção",
      "tempo",
      "temperatura",
      "técnico",
      "balança",
      "didático",
      "trena",
      "fundamental",
      "distância",
    ],
  },
  26: {
    groups: [
      {
        number: 1,
        theme: "Usados para localização",
        words: ["sol", "bússola", "farol", "gps"],
      },
      {
        number: 2,
        theme: "Advérbios de lugar",
        words: ["lá", "aí", "abaixo", "atrás"],
      },
      {
        number: 3,
        theme: "Câmbio do carro",
        words: ["ré", "morto", "primeira", "segunda"],
      },
      {
        number: 4,
        theme: "Sinônimos de pena",
        words: ["dó", "pluma", "punição", "lástima"],
      },
    ],
    startingBoard: [
      "pluma",
      "lástima",
      "sol",
      "gps",
      "farol",
      "aí",
      "ré",
      "bússola",
      "abaixo",
      "morto",
      "segunda",
      "punição",
      "lá",
      "primeira",
      "dó",
      "atrás",
    ],
  },
  27: {
    groups: [
      {
        number: 1,
        theme: "______ d'água",
        words: ["caixa", "pé", "barriga", "queda"],
      },
      {
        number: 2,
        theme: "Partes do corpo",
        words: ["olho", "canela", "sola", "cabelo"],
      },
      {
        number: 3,
        theme: "Animais",
        words: ["boi", "cobra", "burro", "gavião"],
      },
      {
        number: 4,
        theme: "Para carregar coisas",
        words: ["bolsa", "sacola", "mochila", "pasta"],
      },
    ],
    startingBoard: [
      "cabelo",
      "cobra",
      "burro",
      "bolsa",
      "barriga",
      "canela",
      "pasta",
      "gavião",
      "boi",
      "sola",
      "mochila",
      "queda",
      "olho",
      "pé",
      "sacola",
      "caixa",
    ],
  },
  28: {
    groups: [
      {
        number: 1,
        theme: "Municípios de São Paulo",
        words: ["sorocaba", "santos", "marília", "taubaté"],
      },
      {
        number: 2,
        theme: '"""Rios"" do Brasil"',
        words: ["solimões", "franciso", "paraná", "janeiro"],
      },
      {
        number: 3,
        theme: "Pessoas em dupla sertaneja",
        words: ["marrone", "mateus", "maraísa", "simaria"],
      },
      {
        number: 4,
        theme: "ETs ou relacionados",
        words: ["varginha", "bilu", "etevaldo", "rodolfo"],
      },
    ],
    startingBoard: [
      "sorocaba",
      "rodolfo",
      "mateus",
      "taubaté",
      "simaria",
      "marrone",
      "solimões",
      "marília",
      "janeiro",
      "bilu",
      "santos",
      "franciso",
      "paraná",
      "varginha",
      "maraísa",
      "etevaldo",
    ],
  },
  29: {
    groups: [
      {
        number: 1,
        theme: "Sabores de sorvete",
        words: ["chocolate", "baunilha", "morango", "creme"],
      },
      {
        number: 2,
        theme: "Flores",
        words: ["margarida", "carmélia", "hortência", "jasmim"],
      },
      {
        number: 3,
        theme: "Cores",
        words: ["violeta", "rosa", "laranja", "vermelha"],
      },
      {
        number: 4,
        theme: "___ de neve",
        words: ["flocos", "boneco", "bola", "branca"],
      },
    ],
    startingBoard: [
      "jasmim",
      "laranja",
      "rosa",
      "bola",
      "creme",
      "margarida",
      "morango",
      "carmélia",
      "vermelha",
      "baunilha",
      "chocolate",
      "hortência",
      "boneco",
      "branca",
      "violeta",
      "flocos",
    ],
  },
  30: {
    groups: [
      {
        number: 1,
        theme: "Relacionados a vulcão",
        words: ["vulcão", "erupção", "magma", "cratera"],
      },
      {
        number: 2,
        theme: "Tarefas domésticas",
        words: ["cozinha", "limpa", "lava", "passa"],
      },
      {
        number: 3,
        theme: "Atletas",
        words: ["ludador", "canoísta", "triatleta", "goleiro"],
      },
      {
        number: 4,
        theme: "Partes da casa",
        words: ["corredor", "sala", "quarto", "banheiro"],
      },
    ],
    startingBoard: [
      "triatleta",
      "canoísta",
      "goleiro",
      "cozinha",
      "banheiro",
      "cratera",
      "sala",
      "passa",
      "quarto",
      "vulcão",
      "corredor",
      "magma",
      "ludador",
      "lava",
      "limpa",
      "erupção",
    ],
  },
  31: {
    groups: [
      {
        number: 1,
        theme: "Falas de um diretor de cinema",
        words: ["luz", "câmera", "ação", "corta"],
      },
      {
        number: 2,
        theme: "Ações na produção de filmes",
        words: ["dirigir", "gravar", "editar", "atuar"],
      },
      {
        number: 3,
        theme: "Formas de locomoção",
        words: ["andar", "navegar", "pilotar", "pedalar"],
      },
      {
        number: 4,
        theme: "Relacionadas a prédio",
        words: ["cobertura", "portaria", "elevador", "escada"],
      },
    ],
    startingBoard: [
      "pilotar",
      "andar",
      "elevador",
      "luz",
      "editar",
      "dirigir",
      "escada",
      "câmera",
      "atuar",
      "gravar",
      "pedalar",
      "corta",
      "navegar",
      "cobertura",
      "ação",
      "portaria",
    ],
  },
  32: {
    groups: [
      {
        number: 1,
        theme: "Termos jurídicos",
        words: ["notificação", "processo", "depoimento", "evidência"],
      },
      {
        number: 2,
        theme: "Mídia social",
        words: ["página", "recomendação", "perfil", "comentário"],
      },
      {
        number: 3,
        theme: "Realeza",
        words: ["trono", "castelo", "rainha", "corte"],
      },
      {
        number: 4,
        theme: "Tratamentos dentários",
        words: ["coroa", "canal", "aparelho", "limpeza"],
      },
    ],
    startingBoard: [
      "depoimento",
      "evidência",
      "trono",
      "notificação",
      "comentário",
      "coroa",
      "canal",
      "perfil",
      "página",
      "rainha",
      "corte",
      "recomendação",
      "limpeza",
      "processo",
      "aparelho",
      "castelo",
    ],
  },
  33: {
    groups: [
      {
        number: 1,
        theme: "Locais de preservação",
        words: ["parque", "reserva", "santuário", "refúgio"],
      },
      {
        number: 2,
        theme: "Indígenas",
        words: ["aldeia", "pajé", "território", "povo"],
      },
      {
        number: 3,
        theme: "Comunicação em massa",
        words: ["televisão", "jornal", "revista", "internet"],
      },
      {
        number: 4,
        theme: "Elementos químicos",
        words: ["rádio", "índio", "hélio", "gálio"],
      },
    ],
    startingBoard: [
      "parque",
      "reserva",
      "pajé",
      "rádio",
      "território",
      "povo",
      "gálio",
      "aldeia",
      "jornal",
      "televisão",
      "refúgio",
      "revista",
      "santuário",
      "índio",
      "internet",
      "hélio",
    ],
  },
  34: {
    groups: [
      {
        number: 1,
        theme: "Objetos dos Teletubbies",
        words: ["bolsa", "chapéu", "bola", "patinete"],
      },
      {
        number: 2,
        theme: "Acessórios",
        words: ["cinto", "brinco", "colar", "óculos"],
      },
      {
        number: 3,
        theme: "Brinquedos",
        words: ["patins", "carrinho", "boneca", "blocos"],
      },
      {
        number: 4,
        theme: "Ações em papel",
        words: ["recorta", "amassa", "grampeia", "dobra"],
      },
    ],
    startingBoard: [
      "cinto",
      "bola",
      "bolsa",
      "blocos",
      "recorta",
      "carrinho",
      "dobra",
      "grampeia",
      "patins",
      "patinete",
      "chapéu",
      "brinco",
      "colar",
      "amassa",
      "boneca",
      "óculos",
    ],
  },
  35: {
    groups: [
      {
        number: 1,
        theme: "Derivados de leite",
        words: ["queijo", "requeijão", "ricota", "leite condensado"],
      },
      {
        number: 2,
        theme: "Higiene pessoal",
        words: ["sabonete", "shampoo", "fio dental", "desodorante"],
      },
      {
        number: 3,
        theme: "Produtos de limpeza",
        words: ["detergente", "balde", "esponja", "flanela"],
      },
      {
        number: 4,
        theme: "Chamados pela marca",
        words: ["bombril", "cotonete", "maizena", "catupiry"],
      },
    ],
    startingBoard: [
      "ricota",
      "fio dental",
      "cotonete",
      "balde",
      "maizena",
      "flanela",
      "esponja",
      "detergente",
      "catupiry",
      "requeijão",
      "sabonete",
      "shampoo",
      "bombril",
      "leite condensado",
      "desodorante",
      "queijo",
    ],
  },
  36: {
    groups: [
      {
        number: 1,
        theme: "Membros do Quarteto Fantástico",
        words: ["fantástico", "invisível", "tocha", "coisa"],
      },
      {
        number: 2,
        theme: "Répteis",
        words: ["cobra", "jacaré", "tartaruga", "iguana"],
      },
      {
        number: 3,
        theme: "Adjetivos com i",
        words: ["incrível", "instável", "íntegro", "inflável"],
      },
      {
        number: 4,
        theme: "Tipos de carne",
        words: ["cupim", "patinho", "costela", "lagarto"],
      },
    ],
    startingBoard: [
      "lagarto",
      "iguana",
      "cupim",
      "fantástico",
      "íntegro",
      "instável",
      "tartaruga",
      "jacaré",
      "costela",
      "incrível",
      "patinho",
      "invisível",
      "inflável",
      "coisa",
      "tocha",
      "cobra",
    ],
  },
  37: {
    groups: [
      {
        number: 1,
        theme: "Tipos de números",
        words: ["pares", "ímpares", "naturais", "inteiros"],
      },
      {
        number: 2,
        theme: "Ferramentas",
        words: ["alicate", "furadeira", "trena", "nível"],
      },
      {
        number: 3,
        theme: "Em grande quantidade",
        words: ["monte", "vários", "múltiplos", "inúmeros"],
      },
      {
        number: 4,
        theme: "Relevos altos",
        words: ["montanha", "pico", "serra", "cume"],
      },
    ],
    startingBoard: [
      "furadeira",
      "pico",
      "monte",
      "alicate",
      "nível",
      "serra",
      "naturais",
      "múltiplos",
      "pares",
      "montanha",
      "trena",
      "vários",
      "inúmeros",
      "cume",
      "ímpares",
      "inteiros",
    ],
  },
  38: {
    groups: [
      {
        number: 1,
        theme: "Doces",
        words: ["bala", "pirulito", "chiclete", "goma"],
      },
      {
        number: 2,
        theme: "Objetos cortantes",
        words: ["faca", "tesoura", "estilete", "canivete"],
      },
      {
        number: 3,
        theme: "Perigo",
        words: ["cortante", "perfurante", "tóxico", "explosivo"],
      },
      {
        number: 4,
        theme: "Partes de roupa",
        words: ["elástico", "botão", "zíper", "bolso"],
      },
    ],
    startingBoard: [
      "explosivo",
      "zíper",
      "estilete",
      "cortante",
      "canivete",
      "chiclete",
      "pirulito",
      "tesoura",
      "botão",
      "tóxico",
      "faca",
      "perfurante",
      "elástico",
      "goma",
      "bala",
      "bolso",
    ],
  },
  39: {
    groups: [
      {
        number: 1,
        theme: "Ferramentas",
        words: ["prego", "parafuso", "porca", "broca"],
      },
      {
        number: 2,
        theme: "Tem na padaria",
        words: ["pão", "baguete", "sonho", "bolo"],
      },
      {
        number: 3,
        theme: "Coisas de igreja",
        words: ["altar", "cálice", "bíblia", "vela"],
      },
      {
        number: 4,
        theme: "Exercícios de musculação",
        words: ["crucifixo", "supino", "agachamento", "rosca"],
      },
    ],
    startingBoard: [
      "vela",
      "bíblia",
      "supino",
      "prego",
      "altar",
      "broca",
      "bolo",
      "porca",
      "cálice",
      "rosca",
      "sonho",
      "baguete",
      "crucifixo",
      "pão",
      "agachamento",
      "parafuso",
    ],
  },
  40: {
    groups: [
      {
        number: 1,
        theme: "Animais marinhos",
        words: ["tartaruga", "caranguejo", "lagosta", "baleia"],
      },
      {
        number: 2,
        theme: "Praia",
        words: ["areia", "onda", "concha", "protetor"],
      },
      {
        number: 3,
        theme: "Fenômenos físicos",
        words: ["calor", "eletricidade", "gravidade", "magnetismo"],
      },
      {
        number: 4,
        theme: "Deserto",
        words: ["cacto", "duna", "oásis", "camelo"],
      },
    ],
    startingBoard: [
      "onda",
      "duna",
      "calor",
      "camelo",
      "magnetismo",
      "tartaruga",
      "gravidade",
      "concha",
      "areia",
      "cacto",
      "oásis",
      "protetor",
      "caranguejo",
      "eletricidade",
      "baleia",
      "lagosta",
    ],
  },
  41: {
    groups: [
      {
        number: 1,
        theme: "Partes do corpo",
        words: ["joelho", "pescoço", "perna", "cintura"],
      },
      {
        number: 2,
        theme: "Afundam na água",
        words: ["ferro", "chumbo", "granito", "mercúrio"],
      },
      {
        number: 3,
        theme: "Flutuam na água",
        words: ["madeira", "isopor", "gelo", "cortiça"],
      },
      {
        number: 4,
        theme: "___ fria(o)",
        words: ["guerra", "boia", "frente", "pé"],
      },
    ],
    startingBoard: [
      "granito",
      "joelho",
      "isopor",
      "mercúrio",
      "boia",
      "chumbo",
      "ferro",
      "guerra",
      "gelo",
      "pescoço",
      "frente",
      "pé",
      "perna",
      "cortiça",
      "madeira",
      "cintura",
    ],
  },
  42: {
    groups: [
      {
        number: 1,
        theme: "Construção",
        words: ["fundação", "revestimento", "piso", "encanamento"],
      },
      {
        number: 2,
        theme: "Profissões",
        words: ["médica", "advogada", "artesã", "programadora"],
      },
      {
        number: 3,
        theme: "Concebe na mente",
        words: ["projeta", "arquiteta", "inventa", "idealiza"],
      },
      {
        number: 4,
        theme: "Podemos bater",
        words: ["bola", "laje", "papo", "massa de bolo"],
      },
    ],
    startingBoard: [
      "piso",
      "fundação",
      "revestimento",
      "advogada",
      "papo",
      "artesã",
      "inventa",
      "projeta",
      "bola",
      "encanamento",
      "programadora",
      "idealiza",
      "massa de bolo",
      "arquiteta",
      "médica",
      "laje",
    ],
  },
  43: {
    groups: [
      {
        number: 1,
        theme: "Rádio",
        words: ["transmissão", "antena", "frequência", "locutor"],
      },
      {
        number: 2,
        theme: "Trem",
        words: ["estação", "trilho", "passageiro", "condutor"],
      },
      {
        number: 3,
        theme: "Conjugações do verbo ser",
        words: ["sou", "era", "fui", "fora"],
      },
      {
        number: 4,
        theme: "Período de tempo",
        words: ["época", "período", "fase", "temporada"],
      },
    ],
    startingBoard: [
      "antena",
      "passageiro",
      "frequência",
      "trilho",
      "locutor",
      "sou",
      "fui",
      "fora",
      "transmissão",
      "fase",
      "era",
      "estação",
      "condutor",
      "período",
      "época",
      "temporada",
    ],
  },
  44: {
    groups: [
      {
        number: 1,
        theme: "Infraestrutura viária",
        words: ["rodovia", "rotatória", "viaduto", "trevo"],
      },
      {
        number: 2,
        theme: "Termos de estatística",
        words: ["média", "mediana", "moda", "desvio"],
      },
      {
        number: 3,
        theme: "Sabores de pizza",
        words: ["marguerita", "pepperoni", "quatro queijos", "portuguesa"],
      },
      {
        number: 4,
        theme: "Humoristas",
        words: ["calabresa", "porchat", "adnet", "werneck"],
      },
    ],
    startingBoard: [
      "adnet",
      "rodovia",
      "porchat",
      "portuguesa",
      "werneck",
      "calabresa",
      "rotatória",
      "pepperoni",
      "marguerita",
      "quatro queijos",
      "viaduto",
      "desvio",
      "trevo",
      "mediana",
      "moda",
      "média",
    ],
  },
  45: {
    groups: [
      {
        number: 1,
        theme: "Sinalização sonora",
        words: ["buzina", "sirene", "apito", "alarme"],
      },
      {
        number: 2,
        theme: "Tempos verbais",
        words: ["pretérito", "futuro", "gerúndio", "particípio"],
      },
      {
        number: 3,
        theme: "Coisa oferecida sem custos",
        words: ["brinde", "presente", "mimo", "cortesia"],
      },
      {
        number: 4,
        theme: "Festa",
        words: ["música", "decoração", "convidado", "bebida"],
      },
    ],
    startingBoard: [
      "música",
      "convidado",
      "particípio",
      "brinde",
      "pretérito",
      "apito",
      "presente",
      "futuro",
      "decoração",
      "cortesia",
      "alarme",
      "gerúndio",
      "buzina",
      "bebida",
      "mimo",
      "sirene",
    ],
  },
  46: {
    groups: [
      {
        number: 1,
        theme: "Estilos de arte",
        words: ["renascentista", "gótica", "cubista", "romântica"],
      },
      {
        number: 2,
        theme: "Sem detalhes",
        words: ["vaga", "abstrata", "superficial", "ampla"],
      },
      {
        number: 3,
        theme: "Cargo ou função",
        words: ["emprego", "trabalho", "serviço", "ocupação"],
      },
      {
        number: 4,
        theme: "Ajuste formal entre partes",
        words: ["acordo", "contrato", "tratado", "compromisso"],
      },
    ],
    startingBoard: [
      "vaga",
      "renascentista",
      "serviço",
      "compromisso",
      "superficial",
      "romântica",
      "cubista",
      "contrato",
      "ocupação",
      "ampla",
      "emprego",
      "trabalho",
      "acordo",
      "tratado",
      "gótica",
      "abstrata",
    ],
  },
  47: {
    groups: [
      {
        number: 1,
        theme: "Relacionados ao Natal",
        words: ["árvore", "ceia", "presente", "noel"],
      },
      {
        number: 2,
        theme: "Feriados",
        words: ["natal", "tiradentes", "trabalhador", "aparecida"],
      },
      {
        number: 3,
        theme: "Capitais",
        words: ["palmas", "recife", "goiânia", "vitória"],
      },
      {
        number: 4,
        theme: "Carros antigos",
        words: ["brasília", "fusca", "chevette", "impala"],
      },
    ],
    startingBoard: [
      "tiradentes",
      "árvore",
      "vitória",
      "brasília",
      "goiânia",
      "natal",
      "palmas",
      "chevette",
      "trabalhador",
      "noel",
      "aparecida",
      "presente",
      "ceia",
      "fusca",
      "impala",
      "recife",
    ],
  },
  48: {
    groups: [
      {
        number: 1,
        theme: "Usamos nos pés",
        words: ["tênis", "sandália", "chuteira", "salto"],
      },
      {
        number: 2,
        theme: "Esportes",
        words: ["futebol", "basquete", "golfe", "boxe"],
      },
      {
        number: 3,
        theme: "Propriedade rural",
        words: ["chácara", "granja", "rancho", "sítio"],
      },
      {
        number: 4,
        theme: "Ministérios do governo",
        words: ["educação", "esporte", "fazenda", "justiça"],
      },
    ],
    startingBoard: [
      "educação",
      "salto",
      "tênis",
      "sítio",
      "chácara",
      "rancho",
      "futebol",
      "chuteira",
      "sandália",
      "basquete",
      "boxe",
      "esporte",
      "fazenda",
      "granja",
      "justiça",
      "golfe",
    ],
  },
  49: {
    groups: [
      {
        number: 1,
        theme: "Tem no banheiro",
        words: ["toalha", "secador", "lixeira", "vaso"],
      },
      {
        number: 2,
        theme: "Estilos de dança",
        words: ["valsa", "flamenco", "bolero", "tango"],
      },
      {
        number: 3,
        theme: "Temperos",
        words: ["páprica", "louro", "salsa", "pimenta"],
      },
      {
        number: 4,
        theme: "Proteção contra vampiros",
        words: ["alho", "cruz", "espelho", "estaca"],
      },
    ],
    startingBoard: [
      "secador",
      "espelho",
      "bolero",
      "pimenta",
      "valsa",
      "lixeira",
      "páprica",
      "estaca",
      "toalha",
      "salsa",
      "alho",
      "flamenco",
      "louro",
      "vaso",
      "tango",
      "cruz",
    ],
  },
  50: {
    groups: [
      {
        number: 1,
        theme: "Músicas de Chitãozinho e Chororó",
        words: ["evidências", "sinônimos", "cabelo", "alô"],
      },
      {
        number: 2,
        theme: "Estudados no português",
        words: ["antônimos", "parônimos", "homônimos", "metáforas"],
      },
      {
        number: 3,
        theme: "Ajudam a comprovar",
        words: ["indícios", "sinais", "vestígios", "rastros"],
      },
      {
        number: 4,
        theme: "Cidades de MG",
        words: ["passos", "contagem", "formiga", "arcos"],
      },
    ],
    startingBoard: [
      "parônimos",
      "indícios",
      "alô",
      "homônimos",
      "passos",
      "cabelo",
      "evidências",
      "arcos",
      "contagem",
      "formiga",
      "sinais",
      "metáforas",
      "antônimos",
      "rastros",
      "vestígios",
      "sinônimos",
    ],
  },
  51: {
    groups: [
      {
        number: 1,
        theme: "Cargos militares",
        words: ["cabo", "sargento", "general", "comandante"],
      },
      {
        number: 2,
        theme: "Eletricidade",
        words: ["corrente", "tensão", "resistência", "circuito"],
      },
      {
        number: 3,
        theme: "Modalidades de corrida",
        words: ["maratona", "revezamento", "obstáculos", "marcha"],
      },
      {
        number: 4,
        theme: "Metais",
        words: ["ferro", "níquel", "bronze", "cobre"],
      },
    ],
    startingBoard: [
      "corrente",
      "marcha",
      "ferro",
      "circuito",
      "níquel",
      "maratona",
      "bronze",
      "cabo",
      "sargento",
      "tensão",
      "cobre",
      "obstáculos",
      "resistência",
      "general",
      "revezamento",
      "comandante",
    ],
  },
  52: {
    groups: [
      {
        number: 1,
        theme: "Podem ser doados",
        words: ["sangue", "medula", "plasma", "plaquetas"],
      },
      {
        number: 2,
        theme: "Indícios em cenas de crime",
        words: ["digital", "dna", "pegada", "resíduo"],
      },
      {
        number: 3,
        theme: "Hormônios",
        words: ["insulina", "estrogênio", "cortisol", "adrenalina"],
      },
      {
        number: 4,
        theme: "Tipos de dispositivo",
        words: ["analógico", "mecânico", "acústico", "óptico"],
      },
    ],
    startingBoard: [
      "insulina",
      "acústico",
      "adrenalina",
      "medula",
      "mecânico",
      "cortisol",
      "resíduo",
      "dna",
      "estrogênio",
      "plasma",
      "plaquetas",
      "pegada",
      "sangue",
      "óptico",
      "analógico",
      "digital",
    ],
  },
  53: {
    groups: [
      {
        number: 1,
        theme: "Filmes de Steven Spilberg",
        words: ["munique", "tubarão", "indiana", "extraterrestre"],
      },
      {
        number: 2,
        theme: "Cidades alemãs",
        words: ["berlim", "hamburgo", "colônia", "frankfurt"],
      },
      {
        number: 3,
        theme: "Produtos cosméticos",
        words: ["perfume", "loção", "creme", "gel"],
      },
      {
        number: 4,
        theme: "Comida ___",
        words: ["japonesa", "italiana", "brasileira", "alemã"],
      },
    ],
    startingBoard: [
      "tubarão",
      "indiana",
      "creme",
      "frankfurt",
      "perfume",
      "hamburgo",
      "italiana",
      "gel",
      "alemã",
      "extraterrestre",
      "munique",
      "berlim",
      "brasileira",
      "colônia",
      "japonesa",
      "loção",
    ],
  },
  54: {
    groups: [
      {
        number: 1,
        theme: "Que mostra interesse",
        words: ["animada", "dedicada", "encantada", "cativada"],
      },
      {
        number: 2,
        theme: "Que é parecida",
        words: ["semenhante", "análoga", "afim", "homogênea"],
      },
      {
        number: 3,
        theme: "Tipos de roupa",
        words: ["casual", "esportiva", "íntima", "uniforme"],
      },
      {
        number: 4,
        theme: "Festa ___",
        words: ["junina", "infantil", "surpresa", "americana"],
      },
    ],
    startingBoard: [
      "afim",
      "animada",
      "infantil",
      "esportiva",
      "encantada",
      "análoga",
      "cativada",
      "uniforme",
      "homogênea",
      "surpresa",
      "dedicada",
      "junina",
      "americana",
      "íntima",
      "semenhante",
      "casual",
    ],
  },
  55: {
    groups: [
      {
        number: 1,
        theme: "Unidades de medida",
        words: ["grama", "litro", "metro", "hectare"],
      },
      {
        number: 2,
        theme: "Partes de Árvores",
        words: ["tronco", "folha", "raíz", "galho"],
      },
      {
        number: 3,
        theme: "Materiais escolares",
        words: ["papel", "lápis", "caneta", "borracha"],
      },
      {
        number: 4,
        theme: "Tem na boca",
        words: ["dente", "gengiva", "língua", "palato"],
      },
    ],
    startingBoard: [
      "palato",
      "folha",
      "hectare",
      "litro",
      "metro",
      "tronco",
      "língua",
      "papel",
      "caneta",
      "grama",
      "borracha",
      "galho",
      "lápis",
      "dente",
      "raíz",
      "gengiva",
    ],
  },
  56: {
    groups: [
      {
        number: 1,
        theme: "Tem raiz",
        words: ["dente", "números", "árvore", "problema"],
      },
      {
        number: 2,
        theme: "Ossos do corpo humano",
        words: ["mandíbula", "fêmur", "falanges", "fíbula"],
      },
      {
        number: 3,
        theme: "Tipos de carne",
        words: ["costela", "alcatra", "lombo", "fraldinha"],
      },
      {
        number: 4,
        theme: "Sinônimos para bonito",
        words: ["filé", "pão", "formoso", "charmoso"],
      },
    ],
    startingBoard: [
      "falanges",
      "lombo",
      "fraldinha",
      "mandíbula",
      "formoso",
      "pão",
      "alcatra",
      "fêmur",
      "costela",
      "números",
      "charmoso",
      "fíbula",
      "dente",
      "árvore",
      "problema",
      "filé",
    ],
  },
  57: {
    groups: [
      {
        number: 1,
        theme: "Acessórios de cabelo",
        words: ["arco", "presilha", "fita", "piranha"],
      },
      {
        number: 2,
        theme: "Materiais de escritório",
        words: ["clips", "régua", "caneta", "pasta"],
      },
      {
        number: 3,
        theme: "Técnicas em investigações",
        words: ["análise", "exame", "interrogação", "grampo"],
      },
      {
        number: 4,
        theme: "Símbolos",
        words: ["chaves", "exclamação", "cerquilha", "barra"],
      },
    ],
    startingBoard: [
      "chaves",
      "caneta",
      "análise",
      "presilha",
      "grampo",
      "pasta",
      "fita",
      "cerquilha",
      "interrogação",
      "arco",
      "clips",
      "régua",
      "barra",
      "exclamação",
      "piranha",
      "exame",
    ],
  },
  58: {
    groups: [
      {
        number: 1,
        theme: "Coisas que atores fazem",
        words: ["papel", "função", "personagem", "interpretação"],
      },
      {
        number: 2,
        theme: "Desenho",
        words: ["rascunho", "linha", "cor", "proporção"],
      },
      {
        number: 3,
        theme: "Álgebra",
        words: ["variável", "constante", "equação", "operação"],
      },
      {
        number: 4,
        theme: "Produção de novelas",
        words: ["roteiro", "cronograma", "gravação", "edição"],
      },
    ],
    startingBoard: [
      "proporção",
      "variável",
      "operação",
      "cor",
      "interpretação",
      "papel",
      "cronograma",
      "equação",
      "linha",
      "rascunho",
      "função",
      "constante",
      "gravação",
      "edição",
      "roteiro",
      "personagem",
    ],
  },
  59: {
    groups: [
      {
        number: 1,
        theme: "Paralelos geográficos",
        words: ["câncer", "capricórnio", "ártico", "antártico"],
      },
      {
        number: 2,
        theme: "Impérios",
        words: ["romano", "mongol", "otomano", "japonês"],
      },
      {
        number: 3,
        theme: "Animais",
        words: ["touro", "leão", "escorpião", "pinguim"],
      },
      {
        number: 4,
        theme: "Raças de gato",
        words: ["persa", "sphynx", "siamês", "angorá"],
      },
    ],
    startingBoard: [
      "japonês",
      "escorpião",
      "angorá",
      "romano",
      "antártico",
      "capricórnio",
      "sphynx",
      "ártico",
      "persa",
      "mongol",
      "touro",
      "pinguim",
      "leão",
      "otomano",
      "câncer",
      "siamês",
    ],
  },
  60: {
    groups: [
      {
        number: 1,
        theme: "Sentimentos do filme Divertidamente",
        words: ["raiva", "tristeza", "alegria", "medo"],
      },
      {
        number: 2,
        theme: "Relacionados à felicidade",
        words: ["contentamento", "satisfação", "júbilo", "regozijo"],
      },
      {
        number: 3,
        theme: "Cabeça (de) ____",
        words: ["fria", "quente", "vento", "dura"],
      },
      {
        number: 4,
        theme: "Sinônimos de fácil",
        words: ["mole", "simples", "tangível", "atingível"],
      },
    ],
    startingBoard: [
      "quente",
      "vento",
      "fria",
      "tangível",
      "satisfação",
      "dura",
      "contentamento",
      "tristeza",
      "regozijo",
      "atingível",
      "júbilo",
      "simples",
      "medo",
      "raiva",
      "alegria",
      "mole",
    ],
  },
  61: {
    groups: [
      {
        number: 1,
        theme: "Objetos de iluminação",
        words: ["abajour", "lustre", "lanterna", "holofote"],
      },
      {
        number: 2,
        theme: "Personagens da Disney",
        words: ["simba", "pluto", "pumba", "bambi"],
      },
      {
        number: 3,
        theme: "Componentes de embarcações",
        words: ["popa", "mastro", "casco", "timão"],
      },
      {
        number: 4,
        theme: "Relacionados a desejos",
        words: ["vela", "poço", "estrela", "lâmpada"],
      },
    ],
    startingBoard: [
      "simba",
      "lustre",
      "lanterna",
      "lâmpada",
      "timão",
      "poço",
      "abajour",
      "vela",
      "estrela",
      "bambi",
      "pumba",
      "mastro",
      "holofote",
      "pluto",
      "popa",
      "casco",
    ],
  },
  62: {
    groups: [
      {
        number: 1,
        theme: "Áreas do direito",
        words: ["civil", "penal", "tributário", "comercial"],
      },
      {
        number: 2,
        theme: "Engenharias",
        words: ["elétrica", "computação", "química", "produção"],
      },
      {
        number: 3,
        theme: "Sinônimos de produção",
        words: ["fabricação", "manufatura", "confecção", "montagem"],
      },
      {
        number: 4,
        theme: "Setores de uma empresa",
        words: ["recursos humanos", "financeiro", "suprimentos", "jurídico"],
      },
    ],
    startingBoard: [
      "suprimentos",
      "produção",
      "elétrica",
      "tributário",
      "comercial",
      "recursos humanos",
      "montagem",
      "penal",
      "manufatura",
      "jurídico",
      "financeiro",
      "confecção",
      "computação",
      "civil",
      "química",
      "fabricação",
    ],
  },
};

export const useUnlimitedData = () => {
  return data;
};
