const data = {
  0: {
    groups: [
      {
        number: 1,
        theme: "Música",
        words: ["acorde", "harmonia", "ritmo", "melodia"],
      },
      {
        number: 2,
        theme: "Formas de pagamento",
        words: ["nota", "moeda", "cartão", "pix"],
      },
      {
        number: 3,
        theme: "Objetos de sentar",
        words: ["banco", "pufe", "sofá", "cadeira"],
      },
      {
        number: 4,
        theme: "Coisas de escola",
        words: ["histórico", "boletim", "prova", "trabalho"],
      },
    ],
    startingBoard: [
      "nota",
      "cadeira",
      "banco",
      "prova",
      "pufe",
      "ritmo",
      "boletim",
      "moeda",
      "sofá",
      "harmonia",
      "trabalho",
      "melodia",
      "cartão",
      "histórico",
      "acorde",
      "pix",
    ],
  },
  1: {
    groups: [
      {
        number: 1,
        theme: "Materiais de construção",
        words: ["cimento", "tijolo", "areia", "pedra"],
      },
      {
        number: 2,
        theme: "Elementos químicos",
        words: ["ferro", "oxigênio", "carbono", "flúor"],
      },
      {
        number: 3,
        theme: "Fogo",
        words: ["fósforo", "isqueiro", "vela", "lampião"],
      },
      {
        number: 4,
        theme: "Esportes aquáticos",
        words: ["surfe", "remo", "natação", "canoagem"],
      },
    ],
    startingBoard: [
      "ferro",
      "cimento",
      "carbono",
      "isqueiro",
      "lampião",
      "vela",
      "tijolo",
      "remo",
      "surfe",
      "areia",
      "oxigênio",
      "natação",
      "pedra",
      "fósforo",
      "flúor",
      "canoagem",
    ],
  },
  2: {
    groups: [
      {
        number: 1,
        theme: "Títulos de nobreza",
        words: ["príncipe", "duque", "marquês", "conde"],
      },
      {
        number: 2,
        theme: "Formas de governo",
        words: ["reino", "estado", "república", "principado"],
      },
      {
        number: 3,
        theme: "Classificação biológica",
        words: ["ordem", "espécie", "classe", "família"],
      },
      {
        number: 4,
        theme: "Títulos de Harry Potter",
        words: ["pedra", "câmara", "prisioneiro", "cálice"],
      },
    ],
    startingBoard: [
      "pedra",
      "prisioneiro",
      "marquês",
      "câmara",
      "ordem",
      "principado",
      "duque",
      "príncipe",
      "reino",
      "classe",
      "estado",
      "república",
      "conde",
      "família",
      "espécie",
      "cálice",
    ],
  },
  3: {
    groups: [
      {
        number: 1,
        theme: "Frutas tropicais",
        words: ["caju", "graviola", "cupuaçu", "lichia"],
      },
      {
        number: 2,
        theme: "Partes de roupa",
        words: ["manga", "botão", "gola", "cós"],
      },
      {
        number: 3,
        theme: "Formas de chocolate",
        words: ["barra", "calda", "ovo", "pó"],
      },
      {
        number: 4,
        theme: "Revestimentos",
        words: ["cobertura", "casca", "capa", "forro"],
      },
    ],
    startingBoard: [
      "botão",
      "pó",
      "manga",
      "lichia",
      "barra",
      "caju",
      "gola",
      "forro",
      "cupuaçu",
      "cós",
      "ovo",
      "capa",
      "cobertura",
      "calda",
      "graviola",
      "casca",
    ],
  },
  4: {
    groups: [
      {
        number: 1,
        theme: "Meios de transporte",
        words: ["condução", "coletivo", "lotação", "comboio"],
      },
      {
        number: 2,
        theme: "Ter o comando",
        words: ["domínio", "controle", "soberania", "posse"],
      },
      {
        number: 3,
        theme: "Partes de um hotel",
        words: ["recepção", "quarto", "corredor", "saguão"],
      },
      {
        number: 4,
        theme: "Fundamentos de futebol",
        words: ["cabeçada", "passe", "chute", "drible"],
      },
    ],
    startingBoard: [
      "chute",
      "domínio",
      "recepção",
      "condução",
      "corredor",
      "drible",
      "passe",
      "controle",
      "comboio",
      "posse",
      "coletivo",
      "cabeçada",
      "saguão",
      "lotação",
      "soberania",
      "quarto",
    ],
  },
  5: {
    groups: [
      {
        number: 1,
        theme: "Tarefas escolares",
        words: ["pergunta", "problema", "questão", "redação"],
      },
      {
        number: 2,
        theme: "Coisas de igreja",
        words: ["relicário", "órgão", "candelabro", "castiçal"],
      },
      {
        number: 3,
        theme: "Órgãos do corpo",
        words: ["rim", "fígado", "baço", "apêndice"],
      },
      {
        number: 4,
        theme: "Pode-se soprar",
        words: ["apito", "resposta", "vela", "bexiga"],
      },
    ],
    startingBoard: [
      "rim",
      "relicário",
      "apito",
      "pergunta",
      "fígado",
      "órgão",
      "resposta",
      "problema",
      "baço",
      "questão",
      "vela",
      "redação",
      "apêndice",
      "candelabro",
      "castiçal",
      "bexiga",
    ],
  },
  6: {
    groups: [
      {
        number: 1,
        theme: "Usados para limpeza",
        words: ["cloro", "água", "pá", "rodo"],
      },
      {
        number: 2,
        theme: "Muda de direção",
        words: ["roda", "vira", "gira", "volve"],
      },
      {
        number: 3,
        theme: "Partes de carro",
        words: ["mola", "eixo", "porta", "poltrona"],
      },
      {
        number: 4,
        theme: "Podem ser infláveis",
        words: ["colchão", "castelo", "colete", "piscina"],
      },
    ],
    startingBoard: [
      "mola",
      "roda",
      "colchão",
      "cloro",
      "eixo",
      "vira",
      "castelo",
      "água",
      "porta",
      "pá",
      "colete",
      "rodo",
      "poltrona",
      "piscina",
      "gira",
      "volve",
    ],
  },
  7: {
    groups: [
      {
        number: 1,
        theme: "Jogo de ___",
        words: ["mesa", "console", "celular", "computador"],
      },
      {
        number: 2,
        theme: "Objetos de casa",
        words: ["cadeira", "sofá", "cama", "fogão"],
      },
      {
        number: 3,
        theme: "Partes da casa",
        words: ["cozinha", "sala", "quarto", "banheiro"],
      },
      {
        number: 4,
        theme: "Conexões",
        words: ["internet", "wi-fi", "bluetooth", "infravermelho"],
      },
    ],
    startingBoard: [
      "console",
      "quarto",
      "bluetooth",
      "banheiro",
      "mesa",
      "cadeira",
      "sala",
      "internet",
      "celular",
      "computador",
      "infravermelho",
      "cozinha",
      "wi-fi",
      "sofá",
      "fogão",
      "cama",
    ],
  },
  8: {
    groups: [
      {
        number: 1,
        theme: "Mar ___",
        words: ["vermelho", "negro", "morto", "mediterrâneo"],
      },
      {
        number: 2,
        theme: "Flores",
        words: ["vaso", "buquê", "coroa", "arranjo"],
      },
      {
        number: 3,
        theme: "Feitos de madeira",
        words: ["caixão", "móveis", "tábua", "violão"],
      },
      {
        number: 4,
        theme: "Tipos de molho",
        words: ["verde", "rosê", "tomate", "tártaro"],
      },
    ],
    startingBoard: [
      "verde",
      "tártaro",
      "vermelho",
      "arranjo",
      "tomate",
      "violão",
      "mediterrâneo",
      "buquê",
      "móveis",
      "morto",
      "tábua",
      "negro",
      "rosê",
      "coroa",
      "vaso",
      "caixão",
    ],
  },
  9: {
    groups: [
      {
        number: 1,
        theme: "Filhotes de animais",
        words: ["larva", "leitão", "bezerro", "girino"],
      },
      {
        number: 2,
        theme: "Espécies de cobra",
        words: ["coral", "verde", "cascavel", "sucuri"],
      },
      {
        number: 3,
        theme: "Aves brasileiras",
        words: ["jacutinga", "bem-te-vi", "tucano", "sabiá"],
      },
      {
        number: 4,
        theme: "Palíndromos",
        words: ["reviver", "arara", "mirim", "anilina"],
      },
    ],
    startingBoard: [
      "sucuri",
      "coral",
      "reviver",
      "mirim",
      "sabiá",
      "tucano",
      "cascavel",
      "bem-te-vi",
      "arara",
      "leitão",
      "jacutinga",
      "girino",
      "verde",
      "anilina",
      "bezerro",
      "larva",
    ],
  },
  10: {
    groups: [
      {
        number: 1,
        theme: "Termos de geometria",
        words: ["ponto", "reta", "plano", "espaço"],
      },
      {
        number: 2,
        theme: "Transportes públicos",
        words: ["ônibus", "trem", "metrô", "bonde"],
      },
      {
        number: 3,
        theme: "Geografia urbana",
        words: ["rua", "bairro", "cidade", "endereço"],
      },
      {
        number: 4,
        theme: "Componentes de uma carta",
        words: ["remetente", "destinatário", "envelope", "selo"],
      },
    ],
    startingBoard: [
      "ponto",
      "endereço",
      "metrô",
      "plano",
      "selo",
      "espaço",
      "rua",
      "bairro",
      "destinatário",
      "cidade",
      "remetente",
      "ônibus",
      "bonde",
      "trem",
      "envelope",
      "reta",
    ],
  },
  11: {
    groups: [
      {
        number: 1,
        theme: "Alterações de fala/voz",
        words: ["gaga", "muda", "fanha", "rouca"],
      },
      {
        number: 2,
        theme: "Objetos astronômicos",
        words: ["estrela", "sol", "planeta", "satélite"],
      },
      {
        number: 3,
        theme: "Cantoras pop",
        words: ["perry", "spears", "j", "lovato"],
      },
      {
        number: 4,
        theme: "Linguagens de programação",
        words: ["lua", "c", "swift", "r"],
      },
    ],
    startingBoard: [
      "perry",
      "spears",
      "j",
      "rouca",
      "fanha",
      "satélite",
      "r",
      "planeta",
      "swift",
      "lua",
      "lovato",
      "sol",
      "muda",
      "estrela",
      "gaga",
      "c",
    ],
  },
  12: {
    groups: [
      {
        number: 1,
        theme: "Os 4 elementos",
        words: ["água", "terra", "fogo", "ar"],
      },
      {
        number: 2,
        theme: "Ambientes aquáticos",
        words: ["cachoeira", "rio", "mar", "lago"],
      },
      {
        number: 3,
        theme: "Tipos de carne",
        words: ["peixe", "frango", "boi", "cordeiro"],
      },
      {
        number: 4,
        theme: "Verbos",
        words: ["nadar", "cozinhar", "voar", "mergulhar"],
      },
    ],
    startingBoard: [
      "lago",
      "peixe",
      "cozinhar",
      "ar",
      "fogo",
      "mar",
      "nadar",
      "mergulhar",
      "boi",
      "frango",
      "cachoeira",
      "rio",
      "cordeiro",
      "terra",
      "voar",
      "água",
    ],
  },
  13: {
    groups: [
      {
        number: 1,
        theme: "Personagens de Chaves",
        words: ["chiquinha", "quico", "florinda", "girafales"],
      },
      {
        number: 2,
        theme: "Partes do corpo",
        words: ["barriga", "cabeça", "braço", "ombro"],
      },
      {
        number: 3,
        theme: "Relacionados ao litoral",
        words: ["costa", "orla", "praia", "baía"],
      },
      {
        number: 4,
        theme: "Estados do Nordeste",
        words: ["alagoas", "pernambuco", "ceará", "sergipe"],
      },
    ],
    startingBoard: [
      "braço",
      "pernambuco",
      "cabeça",
      "florinda",
      "girafales",
      "quico",
      "baía",
      "sergipe",
      "ceará",
      "alagoas",
      "praia",
      "barriga",
      "orla",
      "costa",
      "chiquinha",
      "ombro",
    ],
  },
  14: {
    groups: [
      {
        number: 1,
        theme: "Podem ter no bolo",
        words: ["glacê", "recheio", "calda", "cobertura"],
      },
      {
        number: 2,
        theme: "Conjunto de pessoas",
        words: ["massa", "público", "povo", "população"],
      },
      {
        number: 3,
        theme: "Algo legal ou positivo",
        words: ["show", "maneiro", "beleza", "jóia"],
      },
      {
        number: 4,
        theme: "Eventos de artistas",
        words: ["turnê", "festival", "concerto", "performance"],
      },
    ],
    startingBoard: [
      "massa",
      "glacê",
      "performance",
      "população",
      "jóia",
      "beleza",
      "povo",
      "festival",
      "calda",
      "turnê",
      "concerto",
      "maneiro",
      "show",
      "cobertura",
      "recheio",
      "público",
    ],
  },
  15: {
    groups: [
      {
        number: 1,
        theme: "Onomatopéias",
        words: ["zap", "tic-tac", "pocotó", "cocoricó"],
      },
      {
        number: 2,
        theme: "Vilões do Batman",
        words: ["coringa", "charada", "crocodilo", "pinguim"],
      },
      {
        number: 3,
        theme: "Jogos de cartas",
        words: ["buraco", "pife", "truco", "poker"],
      },
      {
        number: 4,
        theme: "Naipes de cartas",
        words: ["paus", "copas", "espadas", "ouros"],
      },
    ],
    startingBoard: [
      "crocodilo",
      "coringa",
      "cocoricó",
      "pocotó",
      "pife",
      "truco",
      "copas",
      "paus",
      "espadas",
      "charada",
      "buraco",
      "poker",
      "pinguim",
      "ouros",
      "tic-tac",
      "zap",
    ],
  },
  16: {
    groups: [
      {
        number: 1,
        theme: "Substantivos coletivos",
        words: ["clero", "álbum", "arquipélago", "enxame"],
      },
      {
        number: 2,
        theme: "Lugares em uma cidade",
        words: ["igreja", "hospital", "praça", "posto"],
      },
      {
        number: 3,
        theme: "Fotografia",
        words: ["foto", "paisagem", "retrato", "revelar"],
      },
      {
        number: 4,
        theme: "Abelhas",
        words: ["mel", "colméia", "rainha", "operária"],
      },
    ],
    startingBoard: [
      "álbum",
      "igreja",
      "clero",
      "rainha",
      "arquipélago",
      "enxame",
      "retrato",
      "colméia",
      "operária",
      "mel",
      "paisagem",
      "foto",
      "revelar",
      "praça",
      "hospital",
      "posto",
    ],
  },
  17: {
    groups: [
      {
        number: 1,
        theme: "Hierarquia militar",
        words: ["cabo", "soldado", "brigadeiro", "major"],
      },
      {
        number: 2,
        theme: "Doces",
        words: ["beijinho", "cajuzinho", "cocada", "casadinho"],
      },
      {
        number: 3,
        theme: "Bordado",
        words: ["fio", "linha", "agulha", "ponto"],
      },
      {
        number: 4,
        theme: "Frutas redondas",
        words: ["côco", "melão", "melancia", "laranja"],
      },
    ],
    startingBoard: [
      "linha",
      "laranja",
      "beijinho",
      "soldado",
      "casadinho",
      "melancia",
      "major",
      "cajuzinho",
      "fio",
      "cocada",
      "melão",
      "côco",
      "agulha",
      "brigadeiro",
      "ponto",
      "cabo",
    ],
  },
  18: {
    groups: [
      {
        number: 1,
        theme: "Partes de um texto",
        words: ["palavra", "sílaba", "frase", "parágrafo"],
      },
      {
        number: 2,
        theme: "Composição de música",
        words: ["letra", "melodia", "instrumento", "ritmo"],
      },
      {
        number: 3,
        theme: "Mídias impressas",
        words: ["livro", "revista", "quadrinhos", "jornal"],
      },
      {
        number: 4,
        theme: "Podem ser enviados pelo WhatsApp",
        words: ["foto", "vídeo", "áudio", "contato"],
      },
    ],
    startingBoard: [
      "contato",
      "palavra",
      "foto",
      "frase",
      "vídeo",
      "livro",
      "parágrafo",
      "ritmo",
      "instrumento",
      "áudio",
      "quadrinhos",
      "sílaba",
      "jornal",
      "letra",
      "revista",
      "melodia",
    ],
  },
  19: {
    groups: [
      {
        number: 1,
        theme: "Armas medievais",
        words: ["adaga", "maça", "escudo", "lança"],
      },
      {
        number: 2,
        theme: "Tipos de carro",
        words: ["híbrido", "conversível", "esportivo", "perua"],
      },
      {
        number: 3,
        theme: "Artistas de circo",
        words: ["mágico", "malabarista", "domador", "engolidor"],
      },
      {
        number: 4,
        theme: "Peixe-___",
        words: ["palhaço", "voador", "elétrico", "espada"],
      },
    ],
    startingBoard: [
      "espada",
      "adaga",
      "malabarista",
      "conversível",
      "palhaço",
      "maça",
      "mágico",
      "lança",
      "perua",
      "voador",
      "escudo",
      "híbrido",
      "domador",
      "engolidor",
      "esportivo",
      "elétrico",
    ],
  },
  20: {
    groups: [
      {
        number: 1,
        theme: "Animais de estimação",
        words: ["gato", "cachorro", "papagaio", "hamster"],
      },
      {
        number: 2,
        theme: "Meia-___",
        words: ["calça", "noite", "entrada", "dúzia"],
      },
      {
        number: 3,
        theme: "Tipos de roupa",
        words: ["polo", "cardigã", "shorts", "jaqueta"],
      },
      {
        number: 4,
        theme: "Trava-língua famoso",
        words: ["rato", "roupa", "rei", "roma"],
      },
    ],
    startingBoard: [
      "hamster",
      "noite",
      "dúzia",
      "rei",
      "shorts",
      "gato",
      "cardigã",
      "calça",
      "rato",
      "jaqueta",
      "entrada",
      "polo",
      "cachorro",
      "papagaio",
      "roupa",
      "roma",
    ],
  },
  21: {
    groups: [
      {
        number: 1,
        theme: "Tipos de comércio",
        words: ["mercado", "quitanda", "bazar", "boutique"],
      },
      {
        number: 2,
        theme: "Locais de armazenamento",
        words: ["depósito", "despensa", "armazém", "almoxarifado"],
      },
      {
        number: 3,
        theme: "Fundamentos do vôlei",
        words: ["saque", "bloqueio", "levantamento", "corte"],
      },
      {
        number: 4,
        theme: "Faz-se no banco",
        words: ["empréstimo", "financiamento", "pagamento", "investimento"],
      },
    ],
    startingBoard: [
      "levantamento",
      "boutique",
      "pagamento",
      "quitanda",
      "financiamento",
      "bloqueio",
      "investimento",
      "empréstimo",
      "armazém",
      "corte",
      "despensa",
      "almoxarifado",
      "mercado",
      "depósito",
      "bazar",
      "saque",
    ],
  },
  22: {
    groups: [
      {
        number: 1,
        theme: "Ações de culinária",
        words: ["cortar", "fatiar", "ralar", "misturar"],
      },
      {
        number: 2,
        theme: "Ações de animais",
        words: ["picar", "ruminar", "uivar", "rosnar"],
      },
      {
        number: 3,
        theme: "Atividades físicas",
        words: ["nadar", "pular", "saltar", "caminhar"],
      },
      {
        number: 4,
        theme: "Substantivos",
        words: ["altar", "caviar", "celular", "radar"],
      },
    ],
    startingBoard: [
      "picar",
      "nadar",
      "caviar",
      "pular",
      "rosnar",
      "cortar",
      "altar",
      "misturar",
      "fatiar",
      "ralar",
      "celular",
      "caminhar",
      "uivar",
      "radar",
      "ruminar",
      "saltar",
    ],
  },
  23: {
    groups: [
      {
        number: 1,
        theme: "Futebol",
        words: ["gol", "lateral", "escanteio", "pênalti"],
      },
      {
        number: 2,
        theme: "Tiro com arco",
        words: ["flecha", "arco", "corda", "tiro"],
      },
      {
        number: 3,
        theme: "Empresas de tecnologia",
        words: ["google", "amazon", "netflix", "cisco"],
      },
      {
        number: 4,
        theme: "Sinônimos de objetivo",
        words: ["alvo", "meta", "fim", "propósito"],
      },
    ],
    startingBoard: [
      "flecha",
      "corda",
      "amazon",
      "tiro",
      "fim",
      "arco",
      "escanteio",
      "lateral",
      "google",
      "alvo",
      "netflix",
      "cisco",
      "propósito",
      "pênalti",
      "gol",
      "meta",
    ],
  },
  24: {
    groups: [
      {
        number: 1,
        theme: "Cuidados para plantas",
        words: ["colher", "plantar", "regar", "cortar"],
      },
      {
        number: 2,
        theme: "Objetos com pontas",
        words: ["garfo", "palito", "alfinete", "agulha"],
      },
      {
        number: 3,
        theme: "Armas cortantes",
        words: ["faca", "espada", "machado", "canivete"],
      },
      {
        number: 4,
        theme: "Tem no jardim",
        words: ["mangueira", "flor", "planta", "cerca"],
      },
    ],
    startingBoard: [
      "alfinete",
      "regar",
      "garfo",
      "colher",
      "cortar",
      "espada",
      "cerca",
      "flor",
      "faca",
      "planta",
      "canivete",
      "plantar",
      "palito",
      "machado",
      "agulha",
      "mangueira",
    ],
  },
  25: {
    groups: [
      {
        number: 1,
        theme: "Ensino ___",
        words: ["superior", "fundamental", "médio", "técnico"],
      },
      {
        number: 2,
        theme: "Tipos de livro",
        words: ["infantil", "ficção", "biografia", "didático"],
      },
      {
        number: 3,
        theme: "Coisas que podemos medir",
        words: ["distância", "peso", "tempo", "temperatura"],
      },
      {
        number: 4,
        theme: "Objetos de medição",
        words: ["trena", "balança", "cronômetro", "termômetro"],
      },
    ],
    startingBoard: [
      "biografia",
      "peso",
      "cronômetro",
      "infantil",
      "médio",
      "superior",
      "termômetro",
      "ficção",
      "tempo",
      "temperatura",
      "técnico",
      "balança",
      "didático",
      "trena",
      "fundamental",
      "distância",
    ],
  },
  26: {
    groups: [
      {
        number: 1,
        theme: "Usados para localização",
        words: ["sol", "bússola", "farol", "gps"],
      },
      {
        number: 2,
        theme: "Advérbios de lugar",
        words: ["lá", "aí", "abaixo", "atrás"],
      },
      {
        number: 3,
        theme: "Câmbio do carro",
        words: ["ré", "morto", "primeira", "segunda"],
      },
      {
        number: 4,
        theme: "Sinônimos de pena",
        words: ["dó", "pluma", "punição", "lástima"],
      },
    ],
    startingBoard: [
      "pluma",
      "lástima",
      "sol",
      "gps",
      "farol",
      "aí",
      "ré",
      "bússola",
      "abaixo",
      "morto",
      "segunda",
      "punição",
      "lá",
      "primeira",
      "dó",
      "atrás",
    ],
  },
  27: {
    groups: [
      {
        number: 1,
        theme: "______ d'água",
        words: ["caixa", "pé", "barriga", "queda"],
      },
      {
        number: 2,
        theme: "Partes do corpo",
        words: ["olho", "canela", "sola", "cabelo"],
      },
      {
        number: 3,
        theme: "Animais",
        words: ["boi", "cobra", "burro", "gavião"],
      },
      {
        number: 4,
        theme: "Para carregar coisas",
        words: ["bolsa", "sacola", "mochila", "pasta"],
      },
    ],
    startingBoard: [
      "cabelo",
      "cobra",
      "burro",
      "bolsa",
      "barriga",
      "canela",
      "pasta",
      "gavião",
      "boi",
      "sola",
      "mochila",
      "queda",
      "olho",
      "pé",
      "sacola",
      "caixa",
    ],
  },
  28: {
    groups: [
      {
        number: 1,
        theme: "Municípios de São Paulo",
        words: ["sorocaba", "santos", "marília", "taubaté"],
      },
      {
        number: 2,
        theme: '"""Rios"" do Brasil"',
        words: ["solimões", "franciso", "paraná", "janeiro"],
      },
      {
        number: 3,
        theme: "Pessoas em dupla sertaneja",
        words: ["marrone", "mateus", "maraísa", "simaria"],
      },
      {
        number: 4,
        theme: "ETs ou relacionados",
        words: ["varginha", "bilu", "etevaldo", "rodolfo"],
      },
    ],
    startingBoard: [
      "sorocaba",
      "rodolfo",
      "mateus",
      "taubaté",
      "simaria",
      "marrone",
      "solimões",
      "marília",
      "janeiro",
      "bilu",
      "santos",
      "franciso",
      "paraná",
      "varginha",
      "maraísa",
      "etevaldo",
    ],
  },
  29: {
    groups: [
      {
        number: 1,
        theme: "Sabores de sorvete",
        words: ["chocolate", "baunilha", "morango", "creme"],
      },
      {
        number: 2,
        theme: "Flores",
        words: ["margarida", "carmélia", "hortência", "jasmim"],
      },
      {
        number: 3,
        theme: "Cores",
        words: ["violeta", "rosa", "laranja", "vermelha"],
      },
      {
        number: 4,
        theme: "___ de neve",
        words: ["flocos", "boneco", "bola", "branca"],
      },
    ],
    startingBoard: [
      "jasmim",
      "laranja",
      "rosa",
      "bola",
      "creme",
      "margarida",
      "morango",
      "carmélia",
      "vermelha",
      "baunilha",
      "chocolate",
      "hortência",
      "boneco",
      "branca",
      "violeta",
      "flocos",
    ],
  },
  30: {
    groups: [
      {
        number: 1,
        theme: "Relacionados a vulcão",
        words: ["vulcão", "erupção", "magma", "cratera"],
      },
      {
        number: 2,
        theme: "Tarefas domésticas",
        words: ["cozinha", "limpa", "lava", "passa"],
      },
      {
        number: 3,
        theme: "Atletas",
        words: ["ludador", "canoísta", "triatleta", "goleiro"],
      },
      {
        number: 4,
        theme: "Partes da casa",
        words: ["corredor", "sala", "quarto", "banheiro"],
      },
    ],
    startingBoard: [
      "triatleta",
      "canoísta",
      "goleiro",
      "cozinha",
      "banheiro",
      "cratera",
      "sala",
      "passa",
      "quarto",
      "vulcão",
      "corredor",
      "magma",
      "ludador",
      "lava",
      "limpa",
      "erupção",
    ],
  },
  31: {
    groups: [
      {
        number: 1,
        theme: "Falas de um diretor de cinema",
        words: ["luz", "câmera", "ação", "corta"],
      },
      {
        number: 2,
        theme: "Ações na produção de filmes",
        words: ["dirigir", "gravar", "editar", "atuar"],
      },
      {
        number: 3,
        theme: "Formas de locomoção",
        words: ["andar", "navegar", "pilotar", "pedalar"],
      },
      {
        number: 4,
        theme: "Relacionadas a prédio",
        words: ["cobertura", "portaria", "elevador", "escada"],
      },
    ],
    startingBoard: [
      "pilotar",
      "andar",
      "elevador",
      "luz",
      "editar",
      "dirigir",
      "escada",
      "câmera",
      "atuar",
      "gravar",
      "pedalar",
      "corta",
      "navegar",
      "cobertura",
      "ação",
      "portaria",
    ],
  },
  32: {
    groups: [
      {
        number: 1,
        theme: "Termos jurídicos",
        words: ["notificação", "processo", "depoimento", "evidência"],
      },
      {
        number: 2,
        theme: "Mídia social",
        words: ["página", "recomendação", "perfil", "comentário"],
      },
      {
        number: 3,
        theme: "Realeza",
        words: ["trono", "castelo", "rainha", "corte"],
      },
      {
        number: 4,
        theme: "Tratamentos dentários",
        words: ["coroa", "canal", "aparelho", "limpeza"],
      },
    ],
    startingBoard: [
      "depoimento",
      "evidência",
      "trono",
      "notificação",
      "comentário",
      "coroa",
      "canal",
      "perfil",
      "página",
      "rainha",
      "corte",
      "recomendação",
      "limpeza",
      "processo",
      "aparelho",
      "castelo",
    ],
  },
  33: {
    groups: [
      {
        number: 1,
        theme: "Locais de preservação",
        words: ["parque", "reserva", "santuário", "refúgio"],
      },
      {
        number: 2,
        theme: "Indígenas",
        words: ["aldeia", "pajé", "território", "povo"],
      },
      {
        number: 3,
        theme: "Comunicação em massa",
        words: ["televisão", "jornal", "revista", "internet"],
      },
      {
        number: 4,
        theme: "Elementos químicos",
        words: ["rádio", "índio", "hélio", "gálio"],
      },
    ],
    startingBoard: [
      "parque",
      "reserva",
      "pajé",
      "rádio",
      "território",
      "povo",
      "gálio",
      "aldeia",
      "jornal",
      "televisão",
      "refúgio",
      "revista",
      "santuário",
      "índio",
      "internet",
      "hélio",
    ],
  },
  34: {
    groups: [
      {
        number: 1,
        theme: "Objetos dos Teletubbies",
        words: ["bolsa", "chapéu", "bola", "patinete"],
      },
      {
        number: 2,
        theme: "Acessórios",
        words: ["cinto", "brinco", "colar", "óculos"],
      },
      {
        number: 3,
        theme: "Brinquedos",
        words: ["patins", "carrinho", "boneca", "blocos"],
      },
      {
        number: 4,
        theme: "Ações em papel",
        words: ["recorta", "amassa", "grampeia", "dobra"],
      },
    ],
    startingBoard: [
      "cinto",
      "bola",
      "bolsa",
      "blocos",
      "recorta",
      "carrinho",
      "dobra",
      "grampeia",
      "patins",
      "patinete",
      "chapéu",
      "brinco",
      "colar",
      "amassa",
      "boneca",
      "óculos",
    ],
  },
};

export const useUnlimitedData = () => {
  return data;
};
