const data = {
  0: {
    groups: [
      {
        number: 1,
        theme: "TEMPO ÚMIDO",
        words: ["GRANIZO", "CHUVA", "AGUACEIRO", "NEVE"],
      },
      {
        number: 2,
        theme: "EQUIPES NBA",
        words: ["BUCKS", "HEAT", "JAZZ", "NETS"],
      },
      {
        number: 3,
        theme: "TECLAS DE TECLADO",
        words: ["OPÇÃO", "RETORNO", "SHIFT", "TAB"],
      },
      {
        number: 4,
        theme: "PALÍNDROMOS",
        words: ["CAIAQUE", "NÍVEL", "MÃE", "CARRO DE CORRIDA"],
      },
    ],
    startingBoard: [
      "NEVE",
      "NÍVEL",
      "SHIFT",
      "CAIAQUE",
      "HEAT",
      "TAB",
      "BUCKS",
      "RETORNO",
      "JAZZ",
      "GRANIZO",
      "OPÇÃO",
      "CHUVA",
      "AGUACEIRO",
      "CARRO DE CORRIDA",
      "MÃE",
      "NETS",
    ],
  },
  1: {
    groups: [
      {
        number: 1,
        theme: "Os 4 elementos da natureza",
        words: ["Terra", "Vento", "Fogo", "Água"],
      },
      {
        number: 2,
        theme: "Tipos de macacos",
        words: ["Orangotango", "Gibão", "Chimpanzé", "Gorila"],
      },
      {
        number: 3,
        theme: "Bebidas quentes",
        words: ["Café", "Chá", "Latte", "Chocolate quente"],
      },
      {
        number: 4,
        theme: "Períodos de tempo",
        words: ["Ano", "Semana", "Século", "Mês"],
      },
    ],
    startingBoard: [
      "Vento",
      "Fogo",
      "Semana",
      "Latte",
      "Chocolate quente",
      "Terra",
      "Água",
      "Gibão",
      "Mês",
      "Café",
      "Orangotango",
      "Chá",
      "Chimpanzé",
      "Gorila",
      "Século",
      "Ano",
    ],
  },
  2: {
    groups: [
      {
        number: 1,
        theme: "Títulos de Chefe de Estado",
        words: ["Rei", "Presidente", "Primeiro Ministro", "Chanceler"],
      },
      {
        number: 2,
        theme: "Oceanos",
        words: ["Índico", "Pacífico", "Atlântico", "Ártico"],
      },
      {
        number: 3,
        theme: "Roupas começando com S",
        words: ["Camisa", "Meias", "Shorts", "Saia"],
      },
      {
        number: 4,
        theme: "Talheres",
        words: ["Copo", "Prato", "Faca", "Garfo"],
      },
    ],
    startingBoard: [
      "Faca",
      "Saia",
      "Copo",
      "Prato",
      "Ártico",
      "Garfo",
      "Índico",
      "Chanceler",
      "Shorts",
      "Atlântico",
      "Camisa",
      "Presidente",
      "Primeiro Ministro",
      "Rei",
      "Pacífico",
      "Meias",
    ],
  },
  3: {
    groups: [
      {
        number: 1,
        theme: "Palavras descrevendo tamanho",
        words: ["Longo", "Curto", "Grande", "Pequeno"],
      },
      {
        number: 2,
        theme: "Tipos de cabelo",
        words: ["Encaracolado", "Liso", "Ondulado", "Anelado"],
      },
      {
        number: 3,
        theme: "Coisas que você pode colocar na sua cabeça",
        words: ["Óculos", "Máscara", "Chapéu", "Capacete"],
      },
      {
        number: 4,
        theme: "Cores de cabelo",
        words: ["Loiro", "Escuro", "Ruivo", "Branco"],
      },
    ],
    startingBoard: [
      "Máscara",
      "Branco",
      "Escuro",
      "Ruivo",
      "Capacete",
      "Longo",
      "Ondulado",
      "Loiro",
      "Grande",
      "Curto",
      "Encaracolado",
      "Anelado",
      "Liso",
      "Óculos",
      "Chapéu",
      "Pequeno",
    ],
  },
  4: {
    groups: [
      {
        number: 1,
        theme: "Advérbios de frequência",
        words: ["Usualmente", "Frequentemente", "Nunca", "Às vezes"],
      },
      {
        number: 2,
        theme: "Verbos",
        words: ["Jogar", "Dormir", "Correr", "Beber"],
      },
      {
        number: 3,
        theme: "Acessórios de moda",
        words: ["Gravata", "Cachecol", "Casaco", "Sapatos"],
      },
      {
        number: 4,
        theme: "Lares de animais",
        words: ["Ninho", "Aquário", "Canil", "Estábulo"],
      },
    ],
    startingBoard: [
      "Ninho",
      "Gravata",
      "Correr",
      "Dormir",
      "Frequentemente",
      "Jogar",
      "Casaco",
      "Aquário",
      "Canil",
      "Nunca",
      "Sapatos",
      "Beber",
      "Usualmente",
      "Cachecol",
      "Às vezes",
      "Estábulo",
    ],
  },
  5: {
    groups: [
      {
        number: 1,
        theme: "Meses",
        words: ["Junho", "Agosto", "Julho", "Abril"],
      },
      {
        number: 2,
        theme: "Membros da família",
        words: ["Esposa", "Marido", "Irmão", "Mãe"],
      },
      {
        number: 3,
        theme: "Animais",
        words: ["Rato", "Raposa", "Lobo", "Tigre"],
      },
      {
        number: 4,
        theme: "Lojas",
        words: ["Padaria", "Farmácia", "Supermercado", "Livraria"],
      },
    ],
    startingBoard: [
      "Padaria",
      "Lobo",
      "Farmácia",
      "Livraria",
      "Supermercado",
      "Raposa",
      "Agosto",
      "Tigre",
      "Mãe",
      "Irmão",
      "Julho",
      "Marido",
      "Junho",
      "Abril",
      "Rato",
      "Esposa",
    ],
  },
  6: {
    groups: [
      {
        number: 1,
        theme: "Animais de estimação",
        words: ["Cachorro", "Gato", "Coelho", "Galinha"],
      },
      {
        number: 2,
        theme: "Frutas",
        words: ["Uvas", "Melancia", "Cereja", "Limão"],
      },
      {
        number: 3,
        theme: "Comida",
        words: ["Ovos", "Queijo", "Carne", "Arroz"],
      },
      {
        number: 4,
        theme: "Roupas",
        words: ["Luvas", "Meias", "Cachecol", "Botas"],
      },
    ],
    startingBoard: [
      "Cachorro",
      "Arroz",
      "Galinha",
      "Queijo",
      "Melancia",
      "Carne",
      "Gato",
      "Ovos",
      "Coelho",
      "Meias",
      "Botas",
      "Uvas",
      "Cereja",
      "Luvas",
      "Cachecol",
      "Limão",
    ],
  },
  7: {
    groups: [
      {
        number: 1,
        theme: "Comida de café da manhã",
        words: ["Bacon", "Salsicha", "Feijão", "Ovos mexidos"],
      },
      {
        number: 2,
        theme: "Itens de fast food",
        words: ["Hambúrguer", "Batatas fritas", "Refrigerante", "Nuggets"],
      },
      {
        number: 3,
        theme: "Bebidas",
        words: ["Chá", "Café", "Leite", "Chocolate quente"],
      },
      {
        number: 4,
        theme: "Frutas",
        words: ["Laranja", "Maçã", "Uvas", "Pêra"],
      },
    ],
    startingBoard: [
      "Feijão",
      "Uvas",
      "Ovos mexidos",
      "Pêra",
      "Bacon",
      "Refrigerante",
      "Café",
      "Salsicha",
      "Nuggets",
      "Chocolate quente",
      "Leite",
      "Maçã",
      "Chá",
      "Laranja",
      "Hambúrguer",
      "Batatas fritas",
    ],
  },
  8: {
    groups: [
      {
        number: 1,
        theme: "Ciências",
        words: ["Química", "Biologia", "Zoologia", "Física"],
      },
      {
        number: 2,
        theme: "Sinônimos para Frio",
        words: ["Fresco", "Gelado", "Congelante", "Frio"],
      },
      {
        number: 3,
        theme: "Palavras de ligação expressando causa",
        words: ["Porque", "Como", "Desde", "Para"],
      },
      {
        number: 4,
        theme: "Talheres (Vaisselle)",
        words: ["Prato", "Faca", "Colher", "Garfo"],
      },
    ],
    startingBoard: [
      "Gelado",
      "Congelante",
      "Como",
      "Fresco",
      "Para",
      "Zoologia",
      "Física",
      "Garfo",
      "Biologia",
      "Frio",
      "Porque",
      "Desde",
      "Química",
      "Prato",
      "Colher",
      "Faca",
    ],
  },
  9: {
    groups: [
      {
        number: 1,
        theme: "Estações",
        words: ["Primavera", "Verão", "Outono", "Inverno"],
      },
      {
        number: 2,
        theme: "Momentos do dia",
        words: ["Manhã", "Tarde", "Noite", "Madrugada"],
      },
      {
        number: 3,
        theme: "Períodos de tempo",
        words: ["Minuto", "Semana", "Mês", "Ano"],
      },
      {
        number: 4,
        theme: "Preposições indicando tempo",
        words: ["Antes", "Depois", "Durante", "Desde"],
      },
    ],
    startingBoard: [
      "Outono",
      "Antes",
      "Tarde",
      "Madrugada",
      "Minuto",
      "Ano",
      "Durante",
      "Verão",
      "Manhã",
      "Desde",
      "Depois",
      "Semana",
      "Noite",
      "Primavera",
      "Inverno",
      "Mês",
    ],
  },
  10: {
    groups: [
      {
        number: 1,
        theme: "Flores",
        words: ["Margarida", "Tulipa", "Narciso", "Rosa"],
      },
      {
        number: 2,
        theme: "Ferramentas de artista",
        words: ["Tinta aquarela", "Tinta", "Papel", "Pincel"],
      },
      {
        number: 3,
        theme: "Partes de uma cama",
        words: ["Travesseiro", "Colchão", "Lençóis", "Cobertor"],
      },
      {
        number: 4,
        theme: "Telas",
        words: ["Televisão", "Computador", "Cinema", "Smartphone"],
      },
    ],
    startingBoard: [
      "Pincel",
      "Tinta aquarela",
      "Tulipa",
      "Colchão",
      "Travesseiro",
      "Margarida",
      "Tinta",
      "Smartphone",
      "Televisão",
      "Papel",
      "Narciso",
      "Computador",
      "Lençóis",
      "Cobertor",
      "Cinema",
      "Rosa",
    ],
  },
  11: {
    groups: [
      {
        number: 1,
        theme: "Felinos",
        words: ["Leão", "Tigre", "Leopardo", "Gato"],
      },
      {
        number: 2,
        theme: "Marcas de carros de luxo",
        words: ["Jaguar", "Chevrolet", "Rolls Royce", "Aston Martin"],
      },
      {
        number: 3,
        theme: "Personagens de Shrek",
        words: ["Burro", "Fiona", "Lorde Farquaad", "Homem Biscoito"],
      },
      {
        number: 4,
        theme: "Animais de estimação",
        words: ["Cachorro", "Pássaro", "Hamster", "Peixe"],
      },
    ],
    startingBoard: [
      "Tigre",
      "Leopardo",
      "Hamster",
      "Cachorro",
      "Fiona",
      "Gato",
      "Pássaro",
      "Homem Biscoito",
      "Leão",
      "Burro",
      "Aston Martin",
      "Chevrolet",
      "Jaguar",
      "Lorde Farquaad",
      "Rolls Royce",
      "Peixe",
    ],
  },
  12: {
    groups: [
      {
        number: 1,
        theme: "Animais selvagens",
        words: ["Leão", "Camaleão", "Raposa", "Lobo"],
      },
      {
        number: 2,
        theme: "Marcas de carros",
        words: ["Jaguar", "Ford", "Jeep", "Rolls Royce"],
      },
      {
        number: 3,
        theme: "Animais marinhos",
        words: ["Polvo", "Tubarão", "Baleia", "Cavalo-marinho"],
      },
      {
        number: 4,
        theme: "Animais de estimação",
        words: ["Cachorro", "Gato", "Porquinho-da-índia", "Coelho"],
      },
    ],
    startingBoard: [
      "Lobo",
      "Leão",
      "Cachorro",
      "Jeep",
      "Porquinho-da-índia",
      "Ford",
      "Polvo",
      "Coelho",
      "Baleia",
      "Tubarão",
      "Rolls Royce",
      "Jaguar",
      "Gato",
      "Cavalo-marinho",
      "Camaleão",
      "Raposa",
    ],
  },
  13: {
    groups: [
      {
        number: 1,
        theme: "Peças de mobiliário",
        words: ["Cama", "Cadeira", "Armário", "Prateleira"],
      },
      {
        number: 2,
        theme: "Palavras relacionadas ao clima",
        words: ["Sol", "Granizo", "Névoa", "Tempestade"],
      },
      {
        number: 3,
        theme: "Animais bebês",
        words: [
          "Gatinho",
          "Leitão",
          "Filhote de canguru",
          "Filhote de cachorro",
        ],
      },
      {
        number: 4,
        theme: "Personagens de Friends",
        words: ["Ross", "Rachel", "Chandler", "Phoebe"],
      },
    ],
    startingBoard: [
      "Cama",
      "Chandler",
      "Filhote de canguru",
      "Névoa",
      "Prateleira",
      "Granizo",
      "Phoebe",
      "Cadeira",
      "Leitão",
      "Tempestade",
      "Ross",
      "Rachel",
      "Filhote de cachorro",
      "Gatinho",
      "Sol",
      "Armário",
    ],
  },
  14: {
    groups: [
      {
        number: 1,
        theme: "Palavras interrogativas",
        words: ["Quem", "Onde", "Quando", "O que"],
      },
      {
        number: 2,
        theme: "Corpos de água",
        words: ["Oceano", "Rio", "Lago", "Lagoa"],
      },
      {
        number: 3,
        theme: "Pronomes pessoais",
        words: ["Ela", "Ele", "Eles", "Nós"],
      },
      {
        number: 4,
        theme: "Palavras pronunciadas como letras",
        words: ["Mar", "Você", "Sinal", "Por que"],
      },
    ],
    startingBoard: [
      "Você",
      "Rio",
      "O que",
      "Eles",
      "Ele",
      "Onde",
      "Quem",
      "Lago",
      "Ela",
      "Quando",
      "Lagoa",
      "Sinal",
      "Nós",
      "Mar",
      "Oceano",
      "Por que",
    ],
  },
  15: {
    groups: [
      {
        number: 1,
        theme: "Cartas de baralho",
        words: ["Valete", "Dama", "Rei", "Ás"],
      },
      {
        number: 2,
        theme: "Títulos de nobreza",
        words: ["Príncipe", "Dama", "Senhor", "Princesa"],
      },
      {
        number: 3,
        theme: "Homófonos de letras",
        words: ["Ser", "Olho", "Ver", "Ervilha"],
      },
      {
        number: 4,
        theme: "Bandas de música",
        words: ["U2", "Rolling Stones", "Arctic Monkeys", "Aerosmith"],
      },
    ],
    startingBoard: [
      "Valete",
      "Ás",
      "Príncipe",
      "Ervilha",
      "Princesa",
      "Dama",
      "Olho",
      "Senhor",
      "Aerosmith",
      "Arctic Monkeys",
      "Dama",
      "Rei",
      "Rolling Stones",
      "U2",
      "Ver",
      "Ser",
    ],
  },
  16: {
    groups: [
      {
        number: 1,
        theme: "Substantivos coletivos",
        words: ["clero", "álbum", "arquipélago", "enxame"],
      },
      {
        number: 2,
        theme: "Lugares em uma cidade",
        words: ["igreja", "hospital", "praça", "posto"],
      },
      {
        number: 3,
        theme: "Fotografia",
        words: ["foto", "paisagem", "retrato", "revelar"],
      },
      {
        number: 4,
        theme: "Abelhas",
        words: ["mel", "colméia", "rainha", "operária"],
      },
    ],
    startingBoard: [
      "álbum",
      "igreja",
      "clero",
      "rainha",
      "arquipélago",
      "enxame",
      "retrato",
      "colméia",
      "operária",
      "mel",
      "paisagem",
      "foto",
      "revelar",
      "praça",
      "hospital",
      "posto",
    ],
  },
  17: {
    groups: [
      {
        number: 1,
        theme: "Hierarquia militar",
        words: ["cabo", "soldado", "brigadeiro", "major"],
      },
      {
        number: 2,
        theme: "Doces",
        words: ["beijinho", "cajuzinho", "cocada", "casadinho"],
      },
      {
        number: 3,
        theme: "Bordado",
        words: ["fio", "linha", "agulha", "ponto"],
      },
      {
        number: 4,
        theme: "Frutas redondas",
        words: ["côco", "melão", "melancia", "laranja"],
      },
    ],
    startingBoard: [
      "linha",
      "laranja",
      "beijinho",
      "soldado",
      "casadinho",
      "melancia",
      "major",
      "cajuzinho",
      "fio",
      "cocada",
      "melão",
      "côco",
      "agulha",
      "brigadeiro",
      "ponto",
      "cabo",
    ],
  },
  18: {
    groups: [
      {
        number: 1,
        theme: "Partes de um texto",
        words: ["palavra", "sílaba", "frase", "parágrafo"],
      },
      {
        number: 2,
        theme: "Composição de música",
        words: ["letra", "melodia", "instrumento", "ritmo"],
      },
      {
        number: 3,
        theme: "Mídias impressas",
        words: ["livro", "revista", "quadrinhos", "jornal"],
      },
      {
        number: 4,
        theme: "Podem ser enviados pelo WhatsApp",
        words: ["foto", "vídeo", "áudio", "contato"],
      },
    ],
    startingBoard: [
      "contato",
      "palavra",
      "foto",
      "frase",
      "vídeo",
      "livro",
      "parágrafo",
      "ritmo",
      "instrumento",
      "áudio",
      "quadrinhos",
      "sílaba",
      "jornal",
      "letra",
      "revista",
      "melodia",
    ],
  },
  19: {
    groups: [
      {
        number: 1,
        theme: "Armas medievais",
        words: ["adaga", "maça", "escudo", "lança"],
      },
      {
        number: 2,
        theme: "Tipos de carro",
        words: ["híbrido", "conversível", "esportivo", "perua"],
      },
      {
        number: 3,
        theme: "Artistas de circo",
        words: ["mágico", "malabarista", "domador", "engolidor"],
      },
      {
        number: 4,
        theme: "Peixe-___",
        words: ["palhaço", "voador", "elétrico", "espada"],
      },
    ],
    startingBoard: [
      "espada",
      "adaga",
      "malabarista",
      "conversível",
      "palhaço",
      "maça",
      "mágico",
      "lança",
      "perua",
      "voador",
      "escudo",
      "híbrido",
      "domador",
      "engolidor",
      "esportivo",
      "elétrico",
    ],
  },
  20: {
    groups: [
      {
        number: 1,
        theme: "Animais de estimação",
        words: ["gato", "cachorro", "papagaio", "hamster"],
      },
      {
        number: 2,
        theme: "Meia-___",
        words: ["calça", "noite", "entrada", "dúzia"],
      },
      {
        number: 3,
        theme: "Tipos de roupa",
        words: ["polo", "cardigã", "shorts", "jaqueta"],
      },
      {
        number: 4,
        theme: "Trava-língua famoso",
        words: ["rato", "roupa", "rei", "roma"],
      },
    ],
    startingBoard: [
      "hamster",
      "noite",
      "dúzia",
      "rei",
      "shorts",
      "gato",
      "cardigã",
      "calça",
      "rato",
      "jaqueta",
      "entrada",
      "polo",
      "cachorro",
      "papagaio",
      "roupa",
      "roma",
    ],
  },
  21: {
    groups: [
      {
        number: 1,
        theme: "Tipos de comércio",
        words: ["mercado", "quitanda", "bazar", "boutique"],
      },
      {
        number: 2,
        theme: "Locais de armazenamento",
        words: ["depósito", "despensa", "armazém", "almoxarifado"],
      },
      {
        number: 3,
        theme: "Fundamentos do vôlei",
        words: ["saque", "bloqueio", "levantamento", "corte"],
      },
      {
        number: 4,
        theme: "Faz-se no banco",
        words: ["empréstimo", "financiamento", "pagamento", "investimento"],
      },
    ],
    startingBoard: [
      "levantamento",
      "boutique",
      "pagamento",
      "quitanda",
      "financiamento",
      "bloqueio",
      "investimento",
      "empréstimo",
      "armazém",
      "corte",
      "despensa",
      "almoxarifado",
      "mercado",
      "depósito",
      "bazar",
      "saque",
    ],
  },
  22: {
    groups: [
      {
        number: 1,
        theme: "Ações de culinária",
        words: ["cortar", "fatiar", "ralar", "misturar"],
      },
      {
        number: 2,
        theme: "Ações de animais",
        words: ["picar", "ruminar", "uivar", "rosnar"],
      },
      {
        number: 3,
        theme: "Atividades físicas",
        words: ["nadar", "pular", "saltar", "caminhar"],
      },
      {
        number: 4,
        theme: "Substantivos",
        words: ["altar", "caviar", "celular", "radar"],
      },
    ],
    startingBoard: [
      "picar",
      "nadar",
      "caviar",
      "pular",
      "rosnar",
      "cortar",
      "altar",
      "misturar",
      "fatiar",
      "ralar",
      "celular",
      "caminhar",
      "uivar",
      "radar",
      "ruminar",
      "saltar",
    ],
  },
  23: {
    groups: [
      {
        number: 1,
        theme: "Futebol",
        words: ["gol", "lateral", "escanteio", "pênalti"],
      },
      {
        number: 2,
        theme: "Tiro com arco",
        words: ["flecha", "arco", "corda", "tiro"],
      },
      {
        number: 3,
        theme: "Empresas de tecnologia",
        words: ["google", "amazon", "netflix", "cisco"],
      },
      {
        number: 4,
        theme: "Sinônimos de objetivo",
        words: ["alvo", "meta", "fim", "propósito"],
      },
    ],
    startingBoard: [
      "flecha",
      "corda",
      "amazon",
      "tiro",
      "fim",
      "arco",
      "escanteio",
      "lateral",
      "google",
      "alvo",
      "netflix",
      "cisco",
      "propósito",
      "pênalti",
      "gol",
      "meta",
    ],
  },
  24: {
    groups: [
      {
        number: 1,
        theme: "Cuidados para plantas",
        words: ["colher", "plantar", "regar", "cortar"],
      },
      {
        number: 2,
        theme: "Objetos com pontas",
        words: ["garfo", "palito", "alfinete", "agulha"],
      },
      {
        number: 3,
        theme: "Armas cortantes",
        words: ["faca", "espada", "machado", "canivete"],
      },
      {
        number: 4,
        theme: "Tem no jardim",
        words: ["mangueira", "flor", "planta", "cerca"],
      },
    ],
    startingBoard: [
      "alfinete",
      "regar",
      "garfo",
      "colher",
      "cortar",
      "espada",
      "cerca",
      "flor",
      "faca",
      "planta",
      "canivete",
      "plantar",
      "palito",
      "machado",
      "agulha",
      "mangueira",
    ],
  },
  25: {
    groups: [
      {
        number: 1,
        theme: "Ensino ___",
        words: ["superior", "fundamental", "médio", "técnico"],
      },
      {
        number: 2,
        theme: "Tipos de livro",
        words: ["infantil", "ficção", "biografia", "didático"],
      },
      {
        number: 3,
        theme: "Coisas que podemos medir",
        words: ["distância", "peso", "tempo", "temperatura"],
      },
      {
        number: 4,
        theme: "Objetos de medição",
        words: ["trena", "balança", "cronômetro", "termômetro"],
      },
    ],
    startingBoard: [
      "biografia",
      "peso",
      "cronômetro",
      "infantil",
      "médio",
      "superior",
      "termômetro",
      "ficção",
      "tempo",
      "temperatura",
      "técnico",
      "balança",
      "didático",
      "trena",
      "fundamental",
      "distância",
    ],
  },
  26: {
    groups: [
      {
        number: 1,
        theme: "Usados para localização",
        words: ["sol", "bússola", "farol", "gps"],
      },
      {
        number: 2,
        theme: "Advérbios de lugar",
        words: ["lá", "aí", "abaixo", "atrás"],
      },
      {
        number: 3,
        theme: "Câmbio do carro",
        words: ["ré", "morto", "primeira", "segunda"],
      },
      {
        number: 4,
        theme: "Sinônimos de pena",
        words: ["dó", "pluma", "punição", "lástima"],
      },
    ],
    startingBoard: [
      "pluma",
      "lástima",
      "sol",
      "gps",
      "farol",
      "aí",
      "ré",
      "bússola",
      "abaixo",
      "morto",
      "segunda",
      "punição",
      "lá",
      "primeira",
      "dó",
      "atrás",
    ],
  },
  27: {
    groups: [
      {
        number: 1,
        theme: "______ d'água",
        words: ["caixa", "pé", "barriga", "queda"],
      },
      {
        number: 2,
        theme: "Partes do corpo",
        words: ["olho", "canela", "sola", "cabelo"],
      },
      {
        number: 3,
        theme: "Animais",
        words: ["boi", "cobra", "burro", "gavião"],
      },
      {
        number: 4,
        theme: "Para carregar coisas",
        words: ["bolsa", "sacola", "mochila", "pasta"],
      },
    ],
    startingBoard: [
      "cabelo",
      "cobra",
      "burro",
      "bolsa",
      "barriga",
      "canela",
      "pasta",
      "gavião",
      "boi",
      "sola",
      "mochila",
      "queda",
      "olho",
      "pé",
      "sacola",
      "caixa",
    ],
  },
  28: {
    groups: [
      {
        number: 1,
        theme: "Municípios de São Paulo",
        words: ["sorocaba", "santos", "marília", "taubaté"],
      },
      {
        number: 2,
        theme: '"""Rios"" do Brasil"',
        words: ["solimões", "franciso", "paraná", "janeiro"],
      },
      {
        number: 3,
        theme: "Pessoas em dupla sertaneja",
        words: ["marrone", "mateus", "maraísa", "simaria"],
      },
      {
        number: 4,
        theme: "ETs ou relacionados",
        words: ["varginha", "bilu", "etevaldo", "rodolfo"],
      },
    ],
    startingBoard: [
      "sorocaba",
      "rodolfo",
      "mateus",
      "taubaté",
      "simaria",
      "marrone",
      "solimões",
      "marília",
      "janeiro",
      "bilu",
      "santos",
      "franciso",
      "paraná",
      "varginha",
      "maraísa",
      "etevaldo",
    ],
  },
  29: {
    groups: [
      {
        number: 1,
        theme: "Sabores de sorvete",
        words: ["chocolate", "baunilha", "morango", "creme"],
      },
      {
        number: 2,
        theme: "Flores",
        words: ["margarida", "carmélia", "hortência", "jasmim"],
      },
      {
        number: 3,
        theme: "Cores",
        words: ["violeta", "rosa", "laranja", "vermelha"],
      },
      {
        number: 4,
        theme: "___ de neve",
        words: ["flocos", "boneco", "bola", "branca"],
      },
    ],
    startingBoard: [
      "jasmim",
      "laranja",
      "rosa",
      "bola",
      "creme",
      "margarida",
      "morango",
      "carmélia",
      "vermelha",
      "baunilha",
      "chocolate",
      "hortência",
      "boneco",
      "branca",
      "violeta",
      "flocos",
    ],
  },
  30: {
    groups: [
      {
        number: 1,
        theme: "Relacionados a vulcão",
        words: ["vulcão", "erupção", "magma", "cratera"],
      },
      {
        number: 2,
        theme: "Tarefas domésticas",
        words: ["cozinha", "limpa", "lava", "passa"],
      },
      {
        number: 3,
        theme: "Atletas",
        words: ["ludador", "canoísta", "triatleta", "goleiro"],
      },
      {
        number: 4,
        theme: "Partes da casa",
        words: ["corredor", "sala", "quarto", "banheiro"],
      },
    ],
    startingBoard: [
      "triatleta",
      "canoísta",
      "goleiro",
      "cozinha",
      "banheiro",
      "cratera",
      "sala",
      "passa",
      "quarto",
      "vulcão",
      "corredor",
      "magma",
      "ludador",
      "lava",
      "limpa",
      "erupção",
    ],
  },
  31: {
    groups: [
      {
        number: 1,
        theme: "Falas de um diretor de cinema",
        words: ["luz", "câmera", "ação", "corta"],
      },
      {
        number: 2,
        theme: "Ações na produção de filmes",
        words: ["dirigir", "gravar", "editar", "atuar"],
      },
      {
        number: 3,
        theme: "Formas de locomoção",
        words: ["andar", "navegar", "pilotar", "pedalar"],
      },
      {
        number: 4,
        theme: "Relacionadas a prédio",
        words: ["cobertura", "portaria", "elevador", "escada"],
      },
    ],
    startingBoard: [
      "pilotar",
      "andar",
      "elevador",
      "luz",
      "editar",
      "dirigir",
      "escada",
      "câmera",
      "atuar",
      "gravar",
      "pedalar",
      "corta",
      "navegar",
      "cobertura",
      "ação",
      "portaria",
    ],
  },
  32: {
    groups: [
      {
        number: 1,
        theme: "Termos jurídicos",
        words: ["notificação", "processo", "depoimento", "evidência"],
      },
      {
        number: 2,
        theme: "Mídia social",
        words: ["página", "recomendação", "perfil", "comentário"],
      },
      {
        number: 3,
        theme: "Realeza",
        words: ["trono", "castelo", "rainha", "corte"],
      },
      {
        number: 4,
        theme: "Tratamentos dentários",
        words: ["coroa", "canal", "aparelho", "limpeza"],
      },
    ],
    startingBoard: [
      "depoimento",
      "evidência",
      "trono",
      "notificação",
      "comentário",
      "coroa",
      "canal",
      "perfil",
      "página",
      "rainha",
      "corte",
      "recomendação",
      "limpeza",
      "processo",
      "aparelho",
      "castelo",
    ],
  },
  33: {
    groups: [
      {
        number: 1,
        theme: "Locais de preservação",
        words: ["parque", "reserva", "santuário", "refúgio"],
      },
      {
        number: 2,
        theme: "Indígenas",
        words: ["aldeia", "pajé", "território", "povo"],
      },
      {
        number: 3,
        theme: "Comunicação em massa",
        words: ["televisão", "jornal", "revista", "internet"],
      },
      {
        number: 4,
        theme: "Elementos químicos",
        words: ["rádio", "índio", "hélio", "gálio"],
      },
    ],
    startingBoard: [
      "parque",
      "reserva",
      "pajé",
      "rádio",
      "território",
      "povo",
      "gálio",
      "aldeia",
      "jornal",
      "televisão",
      "refúgio",
      "revista",
      "santuário",
      "índio",
      "internet",
      "hélio",
    ],
  },
  34: {
    groups: [
      {
        number: 1,
        theme: "Objetos dos Teletubbies",
        words: ["bolsa", "chapéu", "bola", "patinete"],
      },
      {
        number: 2,
        theme: "Acessórios",
        words: ["cinto", "brinco", "colar", "óculos"],
      },
      {
        number: 3,
        theme: "Brinquedos",
        words: ["patins", "carrinho", "boneca", "blocos"],
      },
      {
        number: 4,
        theme: "Ações em papel",
        words: ["recorta", "amassa", "grampeia", "dobra"],
      },
    ],
    startingBoard: [
      "cinto",
      "bola",
      "bolsa",
      "blocos",
      "recorta",
      "carrinho",
      "dobra",
      "grampeia",
      "patins",
      "patinete",
      "chapéu",
      "brinco",
      "colar",
      "amassa",
      "boneca",
      "óculos",
    ],
  },
};

export const useUnlimitedData = () => {
  return data;
};
